export const items = [
  { shortName: "abovegroundpool", displayName: "Above Ground Pool" },
  { shortName: "ammo.grenadelauncher.buckshot", displayName: "40mm Shotgun Round" },
  { shortName: "ammo.grenadelauncher.he", displayName: "40mm HE Grenade" },
  { shortName: "ammo.grenadelauncher.smoke", displayName: "40mm Smoke Grenade" },
  { shortName: "ammo.handmade.shell", displayName: "Handmade Shell" },
  { shortName: "ammo.nailgun.nails", displayName: "Nailgun Nails" },
  { shortName: "ammo.pistol", displayName: "Pistol Bullet" },
  { shortName: "ammo.pistol.fire", displayName: "Incendiary Pistol Bullet" },
  { shortName: "ammo.pistol.hv", displayName: "HV Pistol Ammo" },
  { shortName: "ammo.rifle", displayName: "5.56 Rifle Ammo" },
  { shortName: "ammo.rifle.explosive", displayName: "Explosive 5.56 Rifle Ammo" },
  { shortName: "ammo.rifle.hv", displayName: "HV 5.56 Rifle Ammo" },
  { shortName: "ammo.rifle.incendiary", displayName: "Incendiary 5.56 Rifle Ammo" },
  { shortName: "ammo.rocket.basic", displayName: "Rocket" },
  { shortName: "ammo.rocket.fire", displayName: "Incendiary Rocket" },
  { shortName: "ammo.rocket.hv", displayName: "High Velocity Rocket" },
  { shortName: "ammo.rocket.sam", displayName: "SAM Ammo" },
  { shortName: "ammo.rocket.smoke", displayName: "Smoke Rocket WIP!!!!" },
  { shortName: "ammo.shotgun", displayName: "12 Gauge Buckshot" },
  { shortName: "ammo.shotgun.fire", displayName: "12 Gauge Incendiary Shell" },
  { shortName: "ammo.shotgun.slug", displayName: "12 Gauge Slug" },
  { shortName: "antiradpills", displayName: "Anti-Radiation Pills" },
  { shortName: "apple", displayName: "Apple" },
  { shortName: "apple.spoiled", displayName: "Rotten Apple" },
  { shortName: "arcade.machine.chippy", displayName: "Chippy Arcade Game" },
  { shortName: "arrow.bone", displayName: "Bone Arrow" },
  { shortName: "arrow.fire", displayName: "Fire Arrow" },
  { shortName: "arrow.hv", displayName: "High Velocity Arrow" },
  { shortName: "arrow.wooden", displayName: "Wooden Arrow" },
  { shortName: "attire.banditguard", displayName: "Bandit Guard Gear" },
  { shortName: "attire.bunny.onesie", displayName: "Bunny Onesie" },
  { shortName: "attire.bunnyears", displayName: "Bunny Ears" },
  { shortName: "attire.hide.boots", displayName: "Hide Boots" },
  { shortName: "attire.hide.helterneck", displayName: "Hide Halterneck" },
  { shortName: "attire.hide.pants", displayName: "Hide Pants" },
  { shortName: "attire.hide.poncho", displayName: "Hide Poncho" },
  { shortName: "attire.hide.skirt", displayName: "Hide Skirt" },
  { shortName: "attire.hide.vest", displayName: "Hide Vest" },
  { shortName: "attire.nesthat", displayName: "Nest Hat" },
  { shortName: "attire.ninja.suit", displayName: "Ninja Suit" },
  { shortName: "attire.reindeer.headband", displayName: "Reindeer Antlers" },
  { shortName: "autoturret", displayName: "Auto Turret" },
  { shortName: "axe.salvaged", displayName: "Salvaged Axe" },
  { shortName: "bandage", displayName: "Bandage" },
  { shortName: "barrelcostume", displayName: "A Barrel Costume" },
  { shortName: "barricade.concrete", displayName: "Concrete Barricade" },
  { shortName: "barricade.metal", displayName: "Metal Barricade" },
  { shortName: "barricade.sandbags", displayName: "Sandbag Barricade" },
  { shortName: "barricade.stone", displayName: "Stone Barricade" },
  { shortName: "barricade.wood", displayName: "Wooden Barricade" },
  { shortName: "barricade.wood.cover", displayName: "Wooden Barricade Cover" },
  { shortName: "barricade.woodwire", displayName: "Barbed Wooden Barricade" },
  { shortName: "battery.small", displayName: "Battery - Small" },
  { shortName: "bbq", displayName: "Barbeque" },
  { shortName: "beachchair", displayName: "Beach Chair" },
  { shortName: "beachparasol", displayName: "Beach Parasol" },
  { shortName: "beachtable", displayName: "Beach Table" },
  { shortName: "beachtowel", displayName: "Beach Towel" },
  { shortName: "bearmeat", displayName: "Raw Bear Meat" },
  { shortName: "bearmeat.burned", displayName: "Burnt Bear Meat" },
  { shortName: "bearmeat.cooked", displayName: "Cooked Bear Meat" },
  { shortName: "bed", displayName: "Bed" },
  { shortName: "black.berry", displayName: "Black Berry" },
  { shortName: "black.raspberries", displayName: "Black Raspberries" },
  { shortName: "bleach", displayName: "Bleach" },
  { shortName: "blood", displayName: "Blood" },
  { shortName: "blue.berry", displayName: "Blue Berry" },
  { shortName: "blueberries", displayName: "Blueberries" },
  { shortName: "blueprintbase", displayName: "Blueprint" },
  { shortName: "bone.armor.suit", displayName: "Bone Armor" },
  { shortName: "bone.club", displayName: "Bone Club" },
  { shortName: "bone.fragments", displayName: "Bone Fragments" },
  { shortName: "boogieboard", displayName: "Boogie Board" },
  { shortName: "boombox", displayName: "Boom Box" },
  { shortName: "boots.frog", displayName: "Frog Boots" },
  { shortName: "botabag", displayName: "Bota Bag" },
  { shortName: "bow.compound", displayName: "Compound Bow" },
  { shortName: "bow.hunting", displayName: "Hunting Bow" },
  { shortName: "box.repair.bench", displayName: "Repair Bench" },
  { shortName: "box.wooden", displayName: "Wood Storage Box" },
  { shortName: "box.wooden.large", displayName: "Large Wood Box" },
  { shortName: "bucket.helmet", displayName: "Bucket Helmet" },
  { shortName: "bucket.water", displayName: "Water Bucket" },
  { shortName: "building.planner", displayName: "Building Plan" },
  { shortName: "burlap.gloves", displayName: "Leather Gloves" },
  { shortName: "burlap.gloves.new", displayName: "Burlap Gloves" },
  { shortName: "burlap.headwrap", displayName: "Burlap Headwrap" },
  { shortName: "burlap.shirt", displayName: "Burlap Shirt" },
  { shortName: "burlap.shoes", displayName: "Burlap Shoes" },
  { shortName: "burlap.trousers", displayName: "Burlap Trousers" },
  { shortName: "cactusflesh", displayName: "Cactus Flesh" },
  { shortName: "cakefiveyear", displayName: "Birthday Cake" },
  { shortName: "campfire", displayName: "Camp Fire" },
  { shortName: "can.beans", displayName: "Can of Beans" },
  { shortName: "can.beans.empty", displayName: "Empty Can Of Beans" },
  { shortName: "can.tuna", displayName: "Can of Tuna" },
  { shortName: "can.tuna.empty", displayName: "Empty Tuna Can" },
  { shortName: "candycane", displayName: "Candy Cane" },
  { shortName: "candycaneclub", displayName: "Candy Cane Club" },
  { shortName: "car.key", displayName: "Car Key" },
  { shortName: "carburetor1", displayName: "Low Quality Carburetor" },
  { shortName: "carburetor2", displayName: "Medium Quality Carburetor" },
  { shortName: "carburetor3", displayName: "High Quality Carburetor" },
  { shortName: "cardtable", displayName: "Card Table" },
  { shortName: "cassette", displayName: "Cassette - Long" },
  { shortName: "cassette.medium", displayName: "Cassette - Medium" },
  { shortName: "cassette.short", displayName: "Cassette - Short" },
  { shortName: "cctv.camera", displayName: "CCTV Camera" },
  { shortName: "ceilinglight", displayName: "Ceiling Light" },
  { shortName: "chainsaw", displayName: "Chainsaw" },
  { shortName: "chair", displayName: "Chair" },
  { shortName: "charcoal", displayName: "Charcoal" },
  { shortName: "chicken.burned", displayName: "Burnt Chicken" },
  { shortName: "chicken.cooked", displayName: "Cooked Chicken" },
  { shortName: "chicken.raw", displayName: "Raw Chicken Breast" },
  { shortName: "chicken.spoiled", displayName: "Spoiled Chicken" },
  { shortName: "chineselantern", displayName: "Chinese Lantern" },
  { shortName: "chocholate", displayName: "Chocolate Bar" },
  { shortName: "clatter.helmet", displayName: "Clatter Helmet" },
  { shortName: "clone.black.berry", displayName: "Black Berry Clone" },
  { shortName: "clone.blue.berry", displayName: "Blue Berry Clone" },
  { shortName: "clone.corn", displayName: "Corn Clone" },
  { shortName: "clone.green.berry", displayName: "Green Berry Clone" },
  { shortName: "clone.hemp", displayName: "Hemp Clone" },
  { shortName: "clone.potato", displayName: "Potato Clone" },
  { shortName: "clone.pumpkin", displayName: "Pumpkin Plant Clone" },
  { shortName: "clone.red.berry", displayName: "Red Berry Clone" },
  { shortName: "clone.white.berry", displayName: "White Berry Clone" },
  { shortName: "clone.yellow.berry", displayName: "Yellow Berry Clone" },
  { shortName: "cloth", displayName: "Cloth" },
  { shortName: "coal", displayName: "Coal :(" },
  { shortName: "coffeecan.helmet", displayName: "Coffee Can Helmet" },
  { shortName: "coffin.storage", displayName: "Coffin" },
  { shortName: "composter", displayName: "Composter" },
  { shortName: "computerstation", displayName: "Computer Station" },
  { shortName: "connected.speaker", displayName: "Connected Speaker" },
  { shortName: "corn", displayName: "Corn" },
  { shortName: "crankshaft1", displayName: "Low Quality Crankshaft" },
  { shortName: "crankshaft2", displayName: "Medium Quality Crankshaft" },
  { shortName: "crankshaft3", displayName: "High Quality Crankshaft" },
  { shortName: "cratecostume", displayName: "Crate Costume" },
  { shortName: "crossbow", displayName: "Crossbow" },
  { shortName: "crude.oil", displayName: "Crude Oil" },
  { shortName: "cupboard.tool", displayName: "Tool Cupboard" },
  { shortName: "cursedcauldron", displayName: "Cursed Cauldron" },
  { shortName: "deer.skull.mask", displayName: "Bone Helmet" },
  { shortName: "deermeat.burned", displayName: "Burnt Deer Meat" },
  { shortName: "deermeat.cooked", displayName: "Cooked Deer Meat" },
  { shortName: "deermeat.raw", displayName: "Raw Deer Meat" },
  { shortName: "diesel_barrel", displayName: "Diesel Fuel" },
  { shortName: "discoball", displayName: "Disco Ball" },
  { shortName: "discofloor", displayName: "Disco Floor" },
  { shortName: "discofloor.largetiles", displayName: "Disco Floor" },
  { shortName: "diving.fins", displayName: "Diving Fins" },
  { shortName: "diving.mask", displayName: "Diving Mask" },
  { shortName: "diving.tank", displayName: "Diving Tank" },
  { shortName: "diving.wetsuit", displayName: "Wetsuit" },
  { shortName: "door.closer", displayName: "Door Closer" },
  { shortName: "door.double.hinged.metal", displayName: "Sheet Metal Double Door" },
  { shortName: "door.double.hinged.toptier", displayName: "Armored Double Door" },
  { shortName: "door.double.hinged.wood", displayName: "Wood Double Door" },
  { shortName: "door.hinged.industrial.a", displayName: "Industrial Door" },
  { shortName: "door.hinged.metal", displayName: "Sheet Metal Door" },
  { shortName: "door.hinged.toptier", displayName: "Armored Door" },
  { shortName: "door.hinged.wood", displayName: "Wooden Door" },
  { shortName: "door.key", displayName: "Door Key" },
  { shortName: "dragondoorknocker", displayName: "Dragon Door Knocker" },
  { shortName: "drone", displayName: "Drone" },
  { shortName: "dropbox", displayName: "Drop Box" },
  { shortName: "drumkit", displayName: "Junkyard Drum Kit" },
  { shortName: "ducttape", displayName: "Duct Tape" },
  { shortName: "easter.bronzeegg", displayName: "Bronze Egg" },
  { shortName: "easter.goldegg", displayName: "Gold Egg" },
  { shortName: "easter.paintedeggs", displayName: "Painted Egg" },
  { shortName: "easter.silveregg", displayName: "Silver Egg" },
  { shortName: "easterbasket", displayName: "Egg Basket" },
  { shortName: "easterdoorwreath", displayName: "Easter Door Wreath" },
  { shortName: "electric.andswitch", displayName: "AND Switch" },
  { shortName: "electric.audioalarm", displayName: "Audio Alarm" },
  { shortName: "electric.battery.rechargable.large", displayName: "Large Rechargeable Battery" },
  { shortName: "electric.battery.rechargable.medium", displayName: "Medium Rechargeable Battery" },
  { shortName: "electric.battery.rechargable.small", displayName: "Small Rechargeable Battery" },
  { shortName: "electric.blocker", displayName: "Blocker" },
  { shortName: "electric.button", displayName: "Button" },
  { shortName: "electric.cabletunnel", displayName: "Cable Tunnel" },
  { shortName: "electric.counter", displayName: "Counter" },
  { shortName: "electric.doorcontroller", displayName: "Door Controller" },
  { shortName: "electric.flasherlight", displayName: "Flasher Light" },
  { shortName: "electric.fuelgenerator.small", displayName: "Small Generator" },
  { shortName: "electric.generator.small", displayName: "Test Generator" },
  { shortName: "electric.hbhfsensor", displayName: "HBHF Sensor" },
  { shortName: "electric.heater", displayName: "Electric Heater" },
  { shortName: "electric.igniter", displayName: "Igniter" },
  { shortName: "electric.laserdetector", displayName: "Laser Detector" },
  { shortName: "electric.orswitch", displayName: "OR Switch" },
  { shortName: "electric.pressurepad", displayName: "Pressure Pad" },
  { shortName: "electric.random.switch", displayName: "RAND Switch" },
  { shortName: "electric.rf.broadcaster", displayName: "RF Broadcaster" },
  { shortName: "electric.rf.receiver", displayName: "RF Receiver" },
  { shortName: "electric.simplelight", displayName: "Simple Light" },
  { shortName: "electric.sirenlight", displayName: "Siren Light" },
  { shortName: "electric.solarpanel.large", displayName: "Large Solar Panel" },
  { shortName: "electric.splitter", displayName: "Splitter" },
  { shortName: "electric.sprinkler", displayName: "Sprinkler" },
  { shortName: "electric.switch", displayName: "Switch" },
  { shortName: "electric.teslacoil", displayName: "Tesla Coil" },
  { shortName: "electric.timer", displayName: "Timer" },
  { shortName: "electric.xorswitch", displayName: "XOR Switch" },
  { shortName: "electrical.branch", displayName: "Electrical Branch" },
  { shortName: "electrical.combiner", displayName: "Root Combiner" },
  { shortName: "electrical.memorycell", displayName: "Memory Cell" },
  { shortName: "elevator", displayName: "Elevator" },
  { shortName: "explosive.satchel", displayName: "Satchel Charge" },
  { shortName: "explosive.timed", displayName: "Timed Explosive Charge" },
  { shortName: "explosives", displayName: "Explosives" },
  { shortName: "fat.animal", displayName: "Animal Fat" },
  { shortName: "fertilizer", displayName: "Fertilizer" },
  { shortName: "fireplace.stone", displayName: "Stone Fireplace" },
  { shortName: "firework.boomer.blue", displayName: "Blue Boomer" },
  { shortName: "firework.boomer.champagne", displayName: "Champagne Boomer" },
  { shortName: "firework.boomer.green", displayName: "Green Boomer" },
  { shortName: "firework.boomer.orange", displayName: "Orange Boomer" },
  { shortName: "firework.boomer.red", displayName: "Red Boomer" },
  { shortName: "firework.boomer.violet", displayName: "Violet Boomer" },
  { shortName: "firework.romancandle.blue", displayName: "Blue Roman Candle" },
  { shortName: "firework.romancandle.green", displayName: "Green Roman Candle" },
  { shortName: "firework.romancandle.red", displayName: "Red Roman Candle" },
  { shortName: "firework.romancandle.violet", displayName: "Violet Roman Candle" },
  { shortName: "firework.volcano", displayName: "White Volcano Firework" },
  { shortName: "firework.volcano.red", displayName: "Red Volcano Firework" },
  { shortName: "firework.volcano.violet", displayName: "Violet Volcano Firework" },
  { shortName: "fish.anchovy", displayName: "Anchovy" },
  { shortName: "fish.catfish", displayName: "Catfish" },
  { shortName: "fish.cooked", displayName: "Cooked Fish" },
  { shortName: "fish.herring", displayName: "Herring" },
  { shortName: "fish.minnows", displayName: "Minnows" },
  { shortName: "fish.orangeroughy", displayName: "Orange Roughy" },
  { shortName: "fish.raw", displayName: "Raw Fish" },
  { shortName: "fish.salmon", displayName: "Salmon" },
  { shortName: "fish.sardine", displayName: "Sardine" },
  { shortName: "fish.smallshark", displayName: "Small Shark" },
  { shortName: "fish.troutsmall", displayName: "Small Trout" },
  { shortName: "fish.yellowperch", displayName: "Yellow Perch" },
  { shortName: "fishingrod.handmade", displayName: "Handmade Fishing Rod" },
  { shortName: "fishtrap.small", displayName: "Survival Fish Trap" },
  { shortName: "flamethrower", displayName: "Flame Thrower" },
  { shortName: "flameturret", displayName: "Flame Turret" },
  { shortName: "flare", displayName: "Flare" },
  { shortName: "flashlight.held", displayName: "Flashlight" },
  { shortName: "floor.grill", displayName: "Floor grill" },
  { shortName: "floor.ladder.hatch", displayName: "Ladder Hatch" },
  { shortName: "floor.triangle.grill", displayName: "Floor triangle grill" },
  { shortName: "floor.triangle.ladder.hatch", displayName: "Triangle Ladder Hatch" },
  { shortName: "fluid.combiner", displayName: "Fluid Combiner" },
  { shortName: "fluid.splitter", displayName: "Fluid Splitter" },
  { shortName: "fluid.switch", displayName: "Fluid Switch & Pump" },
  { shortName: "fogmachine", displayName: "Fogger-3000" },
  { shortName: "fridge", displayName: "Fridge" },
  { shortName: "fun.bass", displayName: "Shovel Bass" },
  { shortName: "fun.boomboxportable", displayName: "Portable Boom Box" },
  { shortName: "fun.casetterecorder", displayName: "Cassette Recorder" },
  { shortName: "fun.cowbell", displayName: "Cowbell" },
  { shortName: "fun.flute", displayName: "Pan Flute" },
  { shortName: "fun.guitar", displayName: "Acoustic Guitar" },
  { shortName: "fun.jerrycanguitar", displayName: "Jerry Can Guitar" },
  { shortName: "fun.tambourine", displayName: "Canbourine" },
  { shortName: "fun.trumpet", displayName: "Plumber's Trumpet" },
  { shortName: "fun.tuba", displayName: "Sousaphone" },
  { shortName: "furnace", displayName: "Furnace" },
  { shortName: "furnace.large", displayName: "Large Furnace" },
  { shortName: "fuse", displayName: "Electric Fuse" },
  { shortName: "gates.external.high.stone", displayName: "High External Stone Gate" },
  { shortName: "gates.external.high.wood", displayName: "High External Wooden Gate" },
  { shortName: "gears", displayName: "Gears" },
  { shortName: "geiger.counter", displayName: "Geiger Counter" },
  { shortName: "generator.wind.scrap", displayName: "Wind Turbine" },
  { shortName: "ghostsheet", displayName: "Ghost Costume" },
  { shortName: "giantcandycanedecor", displayName: "Giant Candy Decor" },
  { shortName: "giantlollipops", displayName: "Giant Lollipop Decor" },
  { shortName: "gloweyes", displayName: "Glowing Eyes" },
  { shortName: "glue", displayName: "Glue" },
  { shortName: "granolabar", displayName: "Granola Bar" },
  { shortName: "gravestone", displayName: "Gravestone" },
  { shortName: "green.berry", displayName: "Green Berry" },
  { shortName: "grenade.beancan", displayName: "Beancan Grenade" },
  { shortName: "grenade.f1", displayName: "F1 Grenade" },
  { shortName: "grenade.smoke", displayName: "Smoke Grenade" },
  { shortName: "grub", displayName: "Grub" },
  { shortName: "gun.water", displayName: "Water Gun" },
  { shortName: "gunpowder", displayName: "Gun Powder" },
  { shortName: "guntrap", displayName: "Shotgun Trap" },
  { shortName: "habrepair", displayName: "Hab Repair" },
  { shortName: "halloween.candy", displayName: "Halloween Candy" },
  { shortName: "halloween.lootbag.large", displayName: "Large Loot Bag" },
  { shortName: "halloween.lootbag.medium", displayName: "Medium Loot Bag" },
  { shortName: "halloween.lootbag.small", displayName: "Small Loot Bag" },
  { shortName: "halloween.mummysuit", displayName: "Mummy Suit" },
  { shortName: "halloween.surgeonsuit", displayName: "Surgeon Scrubs" },
  { shortName: "hammer", displayName: "Hammer" },
  { shortName: "hammer.salvaged", displayName: "Salvaged Hammer" },
  { shortName: "hat.beenie", displayName: "Beenie Hat" },
  { shortName: "hat.boonie", displayName: "Boonie Hat" },
  { shortName: "hat.bunnyhat", displayName: "Bunny Hat" },
  { shortName: "hat.candle", displayName: "Candle Hat" },
  { shortName: "hat.cap", displayName: "Baseball Cap" },
  { shortName: "hat.dragonmask", displayName: "Dragon Mask" },
  { shortName: "hat.gas.mask", displayName: "Gas Mask" },
  { shortName: "hat.miner", displayName: "Miners Hat" },
  { shortName: "hat.oxmask", displayName: "Ox Mask" },
  { shortName: "hat.ratmask", displayName: "Rat Mask" },
  { shortName: "hat.wolf", displayName: "Wolf Headdress" },
  { shortName: "hatchet", displayName: "Hatchet" },
  { shortName: "hazmatsuit", displayName: "Hazmat Suit" },
  { shortName: "hazmatsuit.spacesuit", displayName: "Space Suit" },
  { shortName: "hazmatsuit_scientist", displayName: "Scientist Suit" },
  { shortName: "hazmatsuit_scientist_peacekeeper", displayName: "Scientist Suit" },
  { shortName: "healingtea", displayName: "Basic Healing Tea" },
  { shortName: "healingtea.advanced", displayName: "Advanced Healing Tea" },
  { shortName: "healingtea.pure", displayName: "Pure Healing Tea" },
  { shortName: "heavy.plate.helmet", displayName: "Heavy Plate Helmet" },
  { shortName: "heavy.plate.jacket", displayName: "Heavy Plate Jacket" },
  { shortName: "heavy.plate.pants", displayName: "Heavy Plate Pants" },
  { shortName: "hitchtroughcombo", displayName: "Hitch & Trough" },
  { shortName: "hobobarrel", displayName: "Hobo Barrel" },
  { shortName: "hoodie", displayName: "Hoodie" },
  { shortName: "horse.armor.roadsign", displayName: "Roadsign Horse Armor" },
  { shortName: "horse.armor.wood", displayName: "Wooden Horse Armor" },
  { shortName: "horse.saddle", displayName: "Horse Saddle" },
  { shortName: "horse.saddlebag", displayName: "Saddle bag" },
  { shortName: "horse.shoes.advanced", displayName: "High Quality Horse Shoes" },
  { shortName: "horse.shoes.basic", displayName: "Basic Horse Shoes" },
  { shortName: "horsedung", displayName: "Horse Dung" },
  { shortName: "horsemeat.burned", displayName: "Burnt Horse Meat" },
  { shortName: "horsemeat.cooked", displayName: "Cooked Horse Meat" },
  { shortName: "horsemeat.raw", displayName: "Raw Horse Meat" },
  { shortName: "hosetool", displayName: "Hose Tool" },
  { shortName: "hq.metal.ore", displayName: "High Quality Metal Ore" },
  { shortName: "humanmeat.burned", displayName: "Burnt Human Meat" },
  { shortName: "humanmeat.cooked", displayName: "Cooked Human Meat" },
  { shortName: "humanmeat.raw", displayName: "Raw Human Meat" },
  { shortName: "humanmeat.spoiled", displayName: "Spoiled Human Meat" },
  { shortName: "icepick.salvaged", displayName: "Salvaged Icepick" },
  { shortName: "innertube", displayName: "Inner Tube" },
  { shortName: "innertube.horse", displayName: "Inner Tube" },
  { shortName: "innertube.unicorn", displayName: "Inner Tube" },
  { shortName: "jacket", displayName: "Jacket" },
  { shortName: "jacket.snow", displayName: "Snow Jacket" },
  { shortName: "jackhammer", displayName: "Jackhammer" },
  { shortName: "jackolantern.angry", displayName: "Jack O Lantern Angry" },
  { shortName: "jackolantern.happy", displayName: "Jack O Lantern Happy" },
  { shortName: "jar.pickle", displayName: "Pickles" },
  { shortName: "jumpsuit.suit", displayName: "Jumpsuit" },
  { shortName: "jumpsuit.suit.blue", displayName: "Blue Jumpsuit" },
  { shortName: "kayak", displayName: "Kayak" },
  { shortName: "keycard_blue", displayName: "Blue Keycard" },
  { shortName: "keycard_green", displayName: "Green Keycard" },
  { shortName: "keycard_red", displayName: "Red Keycard" },
  { shortName: "knife.bone", displayName: "Bone Knife" },
  { shortName: "knife.butcher", displayName: "Butcher Knife" },
  { shortName: "knife.combat", displayName: "Combat Knife" },
  { shortName: "ladder.wooden.wall", displayName: "Wooden Ladder" },
  { shortName: "lantern", displayName: "Lantern" },
  { shortName: "largecandles", displayName: "Large Candle Set" },
  { shortName: "largemedkit", displayName: "Large Medkit" },
  { shortName: "laserlight", displayName: "Laser Light" },
  { shortName: "leather", displayName: "Leather" },
  { shortName: "lmg.m249", displayName: "M249" },
  { shortName: "lock.code", displayName: "Code Lock" },
  { shortName: "lock.key", displayName: "Key Lock" },
  { shortName: "locker", displayName: "Locker" },
  { shortName: "longsword", displayName: "Longsword" },
  { shortName: "lowgradefuel", displayName: "Low Grade Fuel" },
  { shortName: "lunar.firecrackers", displayName: "Firecracker String" },
  { shortName: "mace", displayName: "Mace" },
  { shortName: "machete", displayName: "Machete" },
  { shortName: "mailbox", displayName: "Mail Box" },
  { shortName: "map", displayName: "Paper Map" },
  { shortName: "mask.balaclava", displayName: "Improvised Balaclava" },
  { shortName: "mask.bandana", displayName: "Bandana Mask" },
  { shortName: "maxhealthtea", displayName: "Basic Max Health Tea" },
  { shortName: "maxhealthtea.advanced", displayName: "Advanced Max Health Tea" },
  { shortName: "maxhealthtea.pure", displayName: "Pure Max Health Tea" },
  { shortName: "meat.boar", displayName: "Raw Pork" },
  { shortName: "meat.pork.burned", displayName: "Burnt Pork" },
  { shortName: "meat.pork.cooked", displayName: "Cooked Pork" },
  { shortName: "megaphone", displayName: "Megaphone" },
  { shortName: "metal.facemask", displayName: "Metal Facemask" },
  { shortName: "metal.fragments", displayName: "Metal Fragments" },
  { shortName: "metal.ore", displayName: "Metal Ore" },
  { shortName: "metal.plate.torso", displayName: "Metal Chest Plate" },
  { shortName: "metal.refined", displayName: "High Quality Metal" },
  { shortName: "metalblade", displayName: "Metal Blade" },
  { shortName: "metalpipe", displayName: "Metal Pipe" },
  { shortName: "metalspring", displayName: "Metal Spring" },
  { shortName: "microphonestand", displayName: "Microphone Stand" },
  { shortName: "minihelicopter.repair", displayName: "MC repair" },
  { shortName: "mining.pumpjack", displayName: "Pump Jack" },
  { shortName: "mining.quarry", displayName: "Mining Quarry" },
  { shortName: "mixingtable", displayName: "Mixing Table" },
  { shortName: "mobilephone", displayName: "Mobile Phone" },
  { shortName: "modularcarlift", displayName: "Modular Car Lift" },
  { shortName: "movembermoustache", displayName: "Movember Moustache" },
  { shortName: "movembermoustachecard", displayName: "Card Movember Moustache" },
  { shortName: "multiplegrenadelauncher", displayName: "Multiple Grenade Launcher" },
  { shortName: "mushroom", displayName: "Mushroom" },
  { shortName: "newyeargong", displayName: "New Year Gong" },
  { shortName: "nightvisiongoggles", displayName: "Night Vision Goggles" },
  { shortName: "note", displayName: "Note" },
  { shortName: "oretea", displayName: "Basic Ore Tea" },
  { shortName: "oretea.advanced", displayName: "Advanced Ore Tea" },
  { shortName: "oretea.pure", displayName: "Pure Ore Tea" },
  { shortName: "paddle", displayName: "Paddle" },
  { shortName: "paddlingpool", displayName: "Paddling Pool" },
  { shortName: "pants", displayName: "Pants" },
  { shortName: "pants.shorts", displayName: "Shorts" },
  { shortName: "paper", displayName: "Paper" },
  { shortName: "partyhat", displayName: "Party Hat" },
  { shortName: "photo", displayName: "Photograph" },
  { shortName: "photoframe.landscape", displayName: "Landscape Photo Frame" },
  { shortName: "photoframe.large", displayName: "Large Photo Frame" },
  { shortName: "photoframe.portrait", displayName: "Portrait Photo Frame" },
  { shortName: "piano", displayName: "Wheelbarrow Piano" },
  { shortName: "pickaxe", displayName: "Pickaxe" },
  { shortName: "pistol.eoka", displayName: "Eoka Pistol" },
  { shortName: "pistol.m92", displayName: "M92 Pistol" },
  { shortName: "pistol.nailgun", displayName: "Nailgun" },
  { shortName: "pistol.python", displayName: "Python Revolver" },
  { shortName: "pistol.revolver", displayName: "Revolver" },
  { shortName: "pistol.semiauto", displayName: "Semi-Automatic Pistol" },
  { shortName: "pistol.water", displayName: "Water Pistol" },
  { shortName: "piston1", displayName: "Low Quality Pistons" },
  { shortName: "piston2", displayName: "Medium Quality Pistons" },
  { shortName: "piston3", displayName: "High Quality Pistons" },
  { shortName: "pitchfork", displayName: "Pitchfork" },
  { shortName: "planter.large", displayName: "Large Planter Box" },
  { shortName: "planter.small", displayName: "Small Planter Box" },
  { shortName: "plantfiber", displayName: "Plant Fiber" },
  { shortName: "pookie.bear", displayName: "Pookie Bear" },
  { shortName: "potato", displayName: "Potato" },
  { shortName: "powered.water.purifier", displayName: "Powered Water Purifier" },
  { shortName: "propanetank", displayName: "Empty Propane Tank" },
  { shortName: "pumpkin", displayName: "Pumpkin" },
  { shortName: "pumpkinbasket", displayName: "Pumpkin Bucket" },
  { shortName: "radiationremovetea", displayName: "Rad. Removal Tea" },
  { shortName: "radiationremovetea.advanced", displayName: "Advanced Rad. Removal Tea" },
  { shortName: "radiationremovetea.pure", displayName: "Pure Rad. Removal Tea" },
  { shortName: "radiationresisttea", displayName: "Anti-Rad Tea" },
  { shortName: "radiationresisttea.advanced", displayName: "Adv. Anti-Rad Tea" },
  { shortName: "radiationresisttea.pure", displayName: "Pure Anti-Rad Tea" },
  { shortName: "red.berry", displayName: "Red Berry" },
  { shortName: "research.table", displayName: "Research Table" },
  { shortName: "researchpaper", displayName: "Research Paper" },
  { shortName: "rf.detonator", displayName: "RF Transmitter" },
  { shortName: "rf_pager", displayName: "RF Pager" },
  { shortName: "rifle.ak", displayName: "Assault Rifle" },
  { shortName: "rifle.bolt", displayName: "Bolt Action Rifle" },
  { shortName: "rifle.l96", displayName: "L96 Rifle" },
  { shortName: "rifle.lr300", displayName: "LR-300 Assault Rifle" },
  { shortName: "rifle.m39", displayName: "M39 Rifle" },
  { shortName: "rifle.semiauto", displayName: "Semi-Automatic Rifle" },
  { shortName: "riflebody", displayName: "Rifle Body" },
  { shortName: "riot.helmet", displayName: "Riot Helmet" },
  { shortName: "roadsign.gloves", displayName: "Roadsign Gloves" },
  { shortName: "roadsign.jacket", displayName: "Road Sign Jacket" },
  { shortName: "roadsign.kilt", displayName: "Road Sign Kilt" },
  { shortName: "roadsigns", displayName: "Road Signs" },
  { shortName: "rock", displayName: "Rock" },
  { shortName: "rocket.launcher", displayName: "Rocket Launcher" },
  { shortName: "rope", displayName: "Rope" },
  { shortName: "rug", displayName: "Rug" },
  { shortName: "rug.bear", displayName: "Rug Bear Skin" },
  { shortName: "rustige_egg_a", displayName: "Rustigé Egg - Red" },
  { shortName: "rustige_egg_b", displayName: "Rustigé Egg - Blue" },
  { shortName: "rustige_egg_c", displayName: "Rustigé Egg - Purple" },
  { shortName: "rustige_egg_d", displayName: "Rustigé Egg - Ivory" },
  { shortName: "rustige_egg_e", displayName: "Rustigé Egg - Green" },
  { shortName: "salvaged.cleaver", displayName: "Salvaged Cleaver" },
  { shortName: "salvaged.sword", displayName: "Salvaged Sword" },
  { shortName: "samsite", displayName: "SAM Site" },
  { shortName: "santabeard", displayName: "Santa Beard" },
  { shortName: "santahat", displayName: "Santa Hat" },
  { shortName: "scarecrow", displayName: "Scarecrow" },
  { shortName: "scarecrow.suit", displayName: "Scarecrow Suit" },
  { shortName: "scarecrowhead", displayName: "Scarecrow Wrap" },
  { shortName: "scientistsuit_heavy", displayName: "Heavy Scientist Suit" },
  { shortName: "scrap", displayName: "Scrap" },
  { shortName: "scraptea", displayName: "Basic Scrap Tea" },
  { shortName: "scraptea.advanced", displayName: "Advanced Scrap Tea" },
  { shortName: "scraptea.pure", displayName: "Pure Scrap Tea" },
  { shortName: "scraptransportheli.repair", displayName: "ScrapTransportHeliRepair" },
  { shortName: "searchlight", displayName: "Search Light" },
  { shortName: "secretlabchair", displayName: "Secret Lab Chair" },
  { shortName: "seed.black.berry", displayName: "Black Berry Seed" },
  { shortName: "seed.blue.berry", displayName: "Blue Berry Seed" },
  { shortName: "seed.corn", displayName: "Corn Seed" },
  { shortName: "seed.green.berry", displayName: "Green Berry Seed" },
  { shortName: "seed.hemp", displayName: "Hemp Seed" },
  { shortName: "seed.potato", displayName: "Potato Seed" },
  { shortName: "seed.pumpkin", displayName: "Pumpkin Seed" },
  { shortName: "seed.red.berry", displayName: "Red Berry Seed" },
  { shortName: "seed.white.berry", displayName: "White Berry Seed" },
  { shortName: "seed.yellow.berry", displayName: "Yellow Berry Seed" },
  { shortName: "semibody", displayName: "Semi Automatic Body" },
  { shortName: "sewingkit", displayName: "Sewing Kit" },
  { shortName: "sheetmetal", displayName: "Sheet Metal" },
  { shortName: "shelves", displayName: "Salvaged Shelves" },
  { shortName: "shirt.collared", displayName: "Shirt" },
  { shortName: "shirt.tanktop", displayName: "Tank Top" },
  { shortName: "shoes.boots", displayName: "Boots" },
  { shortName: "shotgun.double", displayName: "Double Barrel Shotgun" },
  { shortName: "shotgun.pump", displayName: "Pump Shotgun" },
  { shortName: "shotgun.spas12", displayName: "Spas-12 Shotgun" },
  { shortName: "shotgun.waterpipe", displayName: "Waterpipe Shotgun" },
  { shortName: "shutter.metal.embrasure.a", displayName: "Metal horizontal embrasure" },
  { shortName: "shutter.metal.embrasure.b", displayName: "Metal Vertical embrasure" },
  { shortName: "shutter.wood.a", displayName: "Wood Shutters" },
  { shortName: "sickle", displayName: "Sickle" },
  { shortName: "sign.hanging", displayName: "Two Sided Hanging Sign" },
  { shortName: "sign.hanging.banner.large", displayName: "Large Banner Hanging" },
  { shortName: "sign.hanging.ornate", displayName: "Two Sided Ornate Hanging Sign" },
  { shortName: "sign.neon.125x125", displayName: "Small Neon Sign" },
  { shortName: "sign.neon.125x215", displayName: "Medium Neon Sign" },
  { shortName: "sign.neon.125x215.animated", displayName: "Medium Animated Neon Sign" },
  { shortName: "sign.neon.xl", displayName: "Large Neon Sign" },
  { shortName: "sign.neon.xl.animated", displayName: "Large Animated Neon Sign" },
  { shortName: "sign.pictureframe.landscape", displayName: "Landscape Picture Frame" },
  { shortName: "sign.pictureframe.portrait", displayName: "Portrait Picture Frame" },
  { shortName: "sign.pictureframe.tall", displayName: "Tall Picture Frame" },
  { shortName: "sign.pictureframe.xl", displayName: "XL Picture Frame" },
  { shortName: "sign.pictureframe.xxl", displayName: "XXL Picture Frame" },
  { shortName: "sign.pole.banner.large", displayName: "Large Banner on pole" },
  { shortName: "sign.post.double", displayName: "Double Sign Post" },
  { shortName: "sign.post.single", displayName: "Single Sign Post" },
  { shortName: "sign.post.town", displayName: "One Sided Town Sign Post" },
  { shortName: "sign.post.town.roof", displayName: "Two Sided Town Sign Post" },
  { shortName: "sign.wooden.huge", displayName: "Huge Wooden Sign" },
  { shortName: "sign.wooden.large", displayName: "Large Wooden Sign" },
  { shortName: "sign.wooden.medium", displayName: "Medium Wooden Sign" },
  { shortName: "sign.wooden.small", displayName: "Small Wooden Sign" },
  { shortName: "skull.human", displayName: "Human Skull" },
  { shortName: "skull.trophy", displayName: "Skull Trophy" },
  { shortName: "skull.trophy.jar", displayName: "Skull Trophy" },
  { shortName: "skull.trophy.jar2", displayName: "Skull Trophy" },
  { shortName: "skull.trophy.table", displayName: "Skull Trophy" },
  { shortName: "skull.wolf", displayName: "Wolf Skull" },
  { shortName: "skull_fire_pit", displayName: "Skull Fire Pit" },
  { shortName: "skulldoorknocker", displayName: "Skull Door Knocker" },
  { shortName: "skullspikes", displayName: "Skull Spikes" },
  { shortName: "skullspikes.candles", displayName: "Skull Spikes" },
  { shortName: "skullspikes.pumpkin", displayName: "Skull Spikes" },
  { shortName: "sled", displayName: "Sled" },
  { shortName: "sled.xmas", displayName: "Sled" },
  { shortName: "sleepingbag", displayName: "Sleeping Bag" },
  { shortName: "small.oil.refinery", displayName: "Small Oil Refinery" },
  { shortName: "smallcandles", displayName: "Small Candle Set" },
  { shortName: "smallwaterbottle", displayName: "Small Water Bottle" },
  { shortName: "smart.alarm", displayName: "Smart Alarm" },
  { shortName: "smart.switch", displayName: "Smart Switch" },
  { shortName: "smg.2", displayName: "Custom SMG" },
  { shortName: "smg.mp5", displayName: "MP5A4" },
  { shortName: "smg.thompson", displayName: "Thompson" },
  { shortName: "smgbody", displayName: "SMG Body" },
  { shortName: "snowball", displayName: "Snowball" },
  { shortName: "snowballgun", displayName: "Snowball Gun" },
  { shortName: "snowmachine", displayName: "Snow Machine" },
  { shortName: "snowman", displayName: "Snowman" },
  { shortName: "sofa", displayName: "Sofa" },
  { shortName: "soundlight", displayName: "Sound Light" },
  { shortName: "sparkplug1", displayName: "Low Quality Spark Plugs" },
  { shortName: "sparkplug2", displayName: "Medium Quality Spark Plugs" },
  { shortName: "sparkplug3", displayName: "High Quality Spark Plugs" },
  { shortName: "spear.stone", displayName: "Stone Spear" },
  { shortName: "spear.wooden", displayName: "Wooden Spear" },
  { shortName: "speargun", displayName: "Speargun" },
  { shortName: "speargun.spear", displayName: "Speargun Spear" },
  { shortName: "spiderweb", displayName: "Spider Webs" },
  { shortName: "spikes.floor", displayName: "Wooden Floor Spikes" },
  { shortName: "spinner.wheel", displayName: "Spinning wheel" },
  { shortName: "spookyspeaker", displayName: "Spooky Speaker" },
  { shortName: "stash.small", displayName: "Small Stash" },
  { shortName: "sticks", displayName: "Sticks" },
  { shortName: "stocking.large", displayName: "SUPER Stocking" },
  { shortName: "stocking.small", displayName: "Small Stocking" },
  { shortName: "stone.pickaxe", displayName: "Stone Pickaxe" },
  { shortName: "stonehatchet", displayName: "Stone Hatchet" },
  { shortName: "stones", displayName: "Stones" },
  { shortName: "storage.monitor", displayName: "Storage Monitor" },
  { shortName: "strobelight", displayName: "Strobe Light" },
  { shortName: "submarine.torpedo.rising", displayName: "Surface torpedo" },
  { shortName: "submarine.torpedo.straight", displayName: "Direct Torpedo" },
  { shortName: "submarineduo", displayName: "Duo Submarine" },
  { shortName: "submarinesolo", displayName: "Solo Submarine" },
  { shortName: "sulfur", displayName: "Sulfur" },
  { shortName: "sulfur.ore", displayName: "Sulfur Ore" },
  { shortName: "sunglasses", displayName: "Sunglasses" },
  { shortName: "sunglasses02black", displayName: "Sunglasses" },
  { shortName: "sunglasses02camo", displayName: "Sunglasses" },
  { shortName: "sunglasses02red", displayName: "Sunglasses" },
  { shortName: "sunglasses03black", displayName: "Sunglasses" },
  { shortName: "sunglasses03chrome", displayName: "Sunglasses" },
  { shortName: "sunglasses03gold", displayName: "Sunglasses" },
  { shortName: "supply.signal", displayName: "Supply Signal" },
  { shortName: "surveycharge", displayName: "Survey Charge" },
  { shortName: "syringe.medical", displayName: "Medical Syringe" },
  { shortName: "table", displayName: "Table" },
  { shortName: "tactical.gloves", displayName: "Tactical Gloves" },
  { shortName: "target.reactive", displayName: "Reactive Target" },
  { shortName: "targeting.computer", displayName: "Targeting Computer" },
  { shortName: "tarp", displayName: "Tarp" },
  { shortName: "techparts", displayName: "Tech Trash" },
  { shortName: "telephone", displayName: "Telephone" },
  { shortName: "tool.binoculars", displayName: "Binoculars" },
  { shortName: "tool.camera", displayName: "Camera" },
  { shortName: "tool.instant_camera", displayName: "Instant Camera" },
  { shortName: "toolgun", displayName: "Garry's Mod Tool Gun" },
  { shortName: "torch", displayName: "Torch" },
  { shortName: "trap.bear", displayName: "Snap Trap" },
  { shortName: "trap.landmine", displayName: "Land Mine" },
  { shortName: "tshirt", displayName: "T-Shirt" },
  { shortName: "tshirt.long", displayName: "Longsleeve T-Shirt" },
  { shortName: "tunalight", displayName: "Tuna Can Lamp" },
  { shortName: "twitch.headset", displayName: "Headset" },
  { shortName: "twitchsunglasses", displayName: "Purple Sunglasses" },
  { shortName: "valve1", displayName: "Low Quality Valves" },
  { shortName: "valve2", displayName: "Medium Quality Valves" },
  { shortName: "valve3", displayName: "High Quality Valves" },
  { shortName: "vehicle.1mod.cockpit", displayName: "Cockpit Vehicle Module" },
  { shortName: "vehicle.1mod.cockpit.armored", displayName: "Armored Cockpit Vehicle Module" },
  { shortName: "vehicle.1mod.cockpit.with.engine", displayName: "Cockpit With Engine Vehicle Module" },
  { shortName: "vehicle.1mod.engine", displayName: "Engine Vehicle Module" },
  { shortName: "vehicle.1mod.flatbed", displayName: "Flatbed Vehicle Module" },
  { shortName: "vehicle.1mod.passengers.armored", displayName: "Armored Passenger Vehicle Module" },
  { shortName: "vehicle.1mod.rear.seats", displayName: "Rear Seats Vehicle Module" },
  { shortName: "vehicle.1mod.storage", displayName: "Storage Vehicle Module" },
  { shortName: "vehicle.1mod.taxi", displayName: "Taxi Vehicle Module" },
  { shortName: "vehicle.2mod.flatbed", displayName: "Large Flatbed Vehicle Module" },
  { shortName: "vehicle.2mod.fuel.tank", displayName: "Fuel Tank Vehicle Module" },
  { shortName: "vehicle.2mod.passengers", displayName: "Passenger Vehicle Module" },
  { shortName: "vehicle.chassis", displayName: "Generic vehicle chassis" },
  { shortName: "vehicle.chassis.2mod", displayName: "Small Chassis" },
  { shortName: "vehicle.chassis.3mod", displayName: "Medium Chassis" },
  { shortName: "vehicle.chassis.4mod", displayName: "Large Chassis" },
  { shortName: "vehicle.module", displayName: "Generic vehicle module" },
  { shortName: "vending.machine", displayName: "Vending Machine" },
  { shortName: "wall.external.high", displayName: "High External Wooden Wall" },
  { shortName: "wall.external.high.ice", displayName: "High Ice Wall" },
  { shortName: "wall.external.high.stone", displayName: "High External Stone Wall" },
  { shortName: "wall.frame.cell", displayName: "Prison Cell Wall" },
  { shortName: "wall.frame.cell.gate", displayName: "Prison Cell Gate" },
  { shortName: "wall.frame.fence", displayName: "Chainlink Fence" },
  { shortName: "wall.frame.fence.gate", displayName: "Chainlink Fence Gate" },
  { shortName: "wall.frame.garagedoor", displayName: "Garage Door" },
  { shortName: "wall.frame.netting", displayName: "Netting" },
  { shortName: "wall.frame.shopfront", displayName: "Shop Front" },
  { shortName: "wall.frame.shopfront.metal", displayName: "Metal Shop Front" },
  { shortName: "wall.graveyard.fence", displayName: "Graveyard Fence" },
  { shortName: "wall.ice.wall", displayName: "Short Ice Wall" },
  { shortName: "wall.window.bars.metal", displayName: "Metal Window Bars" },
  { shortName: "wall.window.bars.toptier", displayName: "Reinforced Glass Window" },
  { shortName: "wall.window.bars.wood", displayName: "Wooden Window Bars" },
  { shortName: "wall.window.glass.reinforced", displayName: "Strengthened Glass Window" },
  { shortName: "watchtower.wood", displayName: "Watch Tower" },
  { shortName: "water", displayName: "Water" },
  { shortName: "water.barrel", displayName: "Water Barrel" },
  { shortName: "water.catcher.large", displayName: "Large Water Catcher" },
  { shortName: "water.catcher.small", displayName: "Small Water Catcher" },
  { shortName: "water.purifier", displayName: "Water Purifier" },
  { shortName: "water.salt", displayName: "Salt Water" },
  { shortName: "waterjug", displayName: "Water Jug" },
  { shortName: "waterpump", displayName: "Water Pump" },
  { shortName: "weapon.mod.8x.scope", displayName: "16x Zoom Scope" },
  { shortName: "weapon.mod.flashlight", displayName: "Weapon flashlight" },
  { shortName: "weapon.mod.holosight", displayName: "Holosight" },
  { shortName: "weapon.mod.lasersight", displayName: "Weapon Lasersight" },
  { shortName: "weapon.mod.muzzleboost", displayName: "Muzzle Boost" },
  { shortName: "weapon.mod.muzzlebrake", displayName: "Muzzle Brake" },
  { shortName: "weapon.mod.silencer", displayName: "Silencer" },
  { shortName: "weapon.mod.simplesight", displayName: "Simple Handmade Sight" },
  { shortName: "weapon.mod.small.scope", displayName: "8x Zoom Scope" },
  { shortName: "white.berry", displayName: "White Berry" },
  { shortName: "wiretool", displayName: "Wire Tool" },
  { shortName: "wolfmeat.burned", displayName: "Burnt Wolf Meat" },
  { shortName: "wolfmeat.cooked", displayName: "Cooked Wolf Meat" },
  { shortName: "wolfmeat.raw", displayName: "Raw Wolf Meat" },
  { shortName: "wolfmeat.spoiled", displayName: "Spoiled Wolf Meat" },
  { shortName: "wood", displayName: "Wood" },
  { shortName: "wood.armor.helmet", displayName: "Wood Armor Helmet" },
  { shortName: "wood.armor.jacket", displayName: "Wood Chestplate" },
  { shortName: "wood.armor.pants", displayName: "Wood Armor Pants" },
  { shortName: "woodcross", displayName: "Wooden Cross" },
  { shortName: "woodtea", displayName: "Basic Wood Tea" },
  { shortName: "woodtea.advanced", displayName: "Advanced Wood Tea" },
  { shortName: "woodtea.pure", displayName: "Pure Wood Tea" },
  { shortName: "workbench1", displayName: "Work Bench Level 1" },
  { shortName: "workbench2", displayName: "Work Bench Level 2" },
  { shortName: "workbench3", displayName: "Work Bench Level 3" },
  { shortName: "workcart", displayName: "Work Cart" },
  { shortName: "worm", displayName: "Worm" },
  { shortName: "wrappedgift", displayName: "Wrapped Gift" },
  { shortName: "wrappingpaper", displayName: "Wrapping Paper" },
  { shortName: "xmas.decoration.baubels", displayName: "Decorative Baubels" },
  { shortName: "xmas.decoration.candycanes", displayName: "Decorative Plastic Candy Canes" },
  { shortName: "xmas.decoration.gingerbreadmen", displayName: "Decorative Gingerbread Men" },
  { shortName: "xmas.decoration.lights", displayName: "Tree Lights" },
  { shortName: "xmas.decoration.pinecone", displayName: "Decorative Pinecones" },
  { shortName: "xmas.decoration.star", displayName: "Star Tree Topper" },
  { shortName: "xmas.decoration.tinsel", displayName: "Decorative Tinsel" },
  { shortName: "xmas.door.garland", displayName: "Festive Doorway Garland" },
  { shortName: "xmas.lightstring", displayName: "Christmas Lights" },
  { shortName: "xmas.lightstring.advanced", displayName: "Deluxe Christmas Lights" },
  { shortName: "xmas.present.large", displayName: "Large Present" },
  { shortName: "xmas.present.medium", displayName: "Medium Present" },
  { shortName: "xmas.present.small", displayName: "Small Present" },
  { shortName: "xmas.tree", displayName: "Christmas Tree" },
  { shortName: "xmas.window.garland", displayName: "Festive Window Garland" },
  { shortName: "xmasdoorwreath", displayName: "Christmas Door Wreath" },
  { shortName: "xylophone", displayName: "Xylobone" },
  { shortName: "yellow.berry", displayName: "Yellow Berry" },
];

// Now you can use the 'items' array here
console.log(items);


// Dynamically build the dropdown list
const buildDropdown = () => {
  const itemDropdown = document.getElementById('itemDropdown');
  itemDropdown.innerHTML = ''; // Clear previous items

  items.forEach(item => {
    const dropdownItem = document.createElement('div');
    dropdownItem.className = 'dropdown-item';
    dropdownItem.dataset.value = item.shortName;
    dropdownItem.innerHTML = `
      <img src="https://wiki.rustclash.com/img/items180/${item.shortName}.png" alt="${item.displayName}">
      ${item.displayName}
    `;
    itemDropdown.appendChild(dropdownItem);
  });
};

// Call the function to build the dropdown when the script is loaded
document.addEventListener('DOMContentLoaded', buildDropdown);
