const items = [
{ shortName: "abovegroundpool", displayName: "Above Ground Pool",showImage: true },
{ shortName: "ammo.grenadelauncher.buckshot", displayName: "40mm Shotgun Round",showImage: true },
{ shortName: "ammo.grenadelauncher.he", displayName: "40mm HE Grenade",showImage: true },
{ shortName: "ammo.grenadelauncher.smoke", displayName: "40mm Smoke Grenade",showImage: true },
{ shortName: "ammo.handmade.shell", displayName: "Handmade Shell",showImage: true },
{ shortName: "ammo.nailgun.nails", displayName: "Nailgun Nails",showImage: true },
{ shortName: "ammo.pistol", displayName: "Pistol Bullet",showImage: true },
{ shortName: "ammo.pistol.fire", displayName: "Incendiary Pistol Bullet",showImage: true },
{ shortName: "ammo.pistol.hv", displayName: "HV Pistol Ammo",showImage: true },
{ shortName: "ammo.rifle", displayName: "5.56 Rifle Ammo",showImage: true },
{ shortName: "ammo.rifle.explosive", displayName: "Explosive 5.56 Rifle Ammo",showImage: true },
{ shortName: "ammo.rifle.hv", displayName: "HV 5.56 Rifle Ammo",showImage: true },
{ shortName: "ammo.rifle.incendiary", displayName: "Incendiary 5.56 Rifle Ammo",showImage: true },
{ shortName: "ammo.rocket.basic", displayName: "Rocket",showImage: true },
{ shortName: "ammo.rocket.fire", displayName: "Incendiary Rocket",showImage: true },
{ shortName: "ammo.rocket.hv", displayName: "High Velocity Rocket",showImage: true },
{ shortName: "ammo.rocket.sam", displayName: "SAM Ammo",showImage: true },
{ shortName: "ammo.rocket.smoke", displayName: "Smoke Rocket WIP!!!!",showImage: true },
{ shortName: "ammo.shotgun", displayName: "12 Gauge Buckshot",showImage: true },
{ shortName: "ammo.shotgun.fire", displayName: "12 Gauge Incendiary Shell",showImage: true },
{ shortName: "ammo.shotgun.slug", displayName: "12 Gauge Slug",showImage: true },
{ shortName: "antiradpills", displayName: "Anti-Radiation Pills",showImage: true },
{ shortName: "apple", displayName: "Apple",showImage: true },
{ shortName: "apple.spoiled", displayName: "Rotten Apple",showImage: true },
{ shortName: "arcade.machine.chippy", displayName: "Chippy Arcade Game",showImage: true },
{ shortName: "arrow.bone", displayName: "Bone Arrow",showImage: true },
{ shortName: "arrow.fire", displayName: "Fire Arrow",showImage: true },
{ shortName: "arrow.hv", displayName: "High Velocity Arrow",showImage: true },
{ shortName: "arrow.wooden", displayName: "Wooden Arrow",showImage: true },
{ shortName: "attire.banditguard", displayName: "Bandit Guard Gear",showImage: true },
{ shortName: "attire.bunny.onesie", displayName: "Bunny Onesie",showImage: true },
{ shortName: "attire.bunnyears", displayName: "Bunny Ears",showImage: true },
{ shortName: "attire.hide.boots", displayName: "Hide Boots",showImage: true },
{ shortName: "attire.hide.helterneck", displayName: "Hide Halterneck",showImage: true },
{ shortName: "attire.hide.pants", displayName: "Hide Pants",showImage: true },
{ shortName: "attire.hide.poncho", displayName: "Hide Poncho",showImage: true },
{ shortName: "attire.hide.skirt", displayName: "Hide Skirt",showImage: true },
{ shortName: "attire.hide.vest", displayName: "Hide Vest",showImage: true },
{ shortName: "attire.nesthat", displayName: "Nest Hat",showImage: true },
{ shortName: "attire.ninja.suit", displayName: "Ninja Suit",showImage: true },
{ shortName: "attire.reindeer.headband", displayName: "Reindeer Antlers",showImage: true },
{ shortName: "autoturret", displayName: "Auto Turret",showImage: true },
{ shortName: "axe.salvaged", displayName: "Salvaged Axe",showImage: true },
{ shortName: "bandage", displayName: "Bandage",showImage: true },
{ shortName: "barrelcostume", displayName: "A Barrel Costume",showImage: true },
{ shortName: "barricade.concrete", displayName: "Concrete Barricade",showImage: true },
{ shortName: "barricade.metal", displayName: "Metal Barricade",showImage: true },
{ shortName: "barricade.sandbags", displayName: "Sandbag Barricade",showImage: true },
{ shortName: "barricade.stone", displayName: "Stone Barricade",showImage: true },
{ shortName: "barricade.wood", displayName: "Wooden Barricade",showImage: true },
{ shortName: "barricade.wood.cover", displayName: "Wooden Barricade Cover",showImage: true },
{ shortName: "barricade.woodwire", displayName: "Barbed Wooden Barricade",showImage: true },
{ shortName: "battery.small", displayName: "Battery - Small",showImage: true },
{ shortName: "bbq", displayName: "Barbeque",showImage: true },
{ shortName: "beachchair", displayName: "Beach Chair",showImage: true },
{ shortName: "beachparasol", displayName: "Beach Parasol",showImage: true },
{ shortName: "beachtable", displayName: "Beach Table",showImage: true },
{ shortName: "beachtowel", displayName: "Beach Towel",showImage: true },
{ shortName: "bearmeat", displayName: "Raw Bear Meat",showImage: true },
{ shortName: "bearmeat.burned", displayName: "Burnt Bear Meat",showImage: true },
{ shortName: "bearmeat.cooked", displayName: "Cooked Bear Meat",showImage: true },
{ shortName: "bed", displayName: "Bed",showImage: true },
{ shortName: "black.berry", displayName: "Black Berry",showImage: true },
{ shortName: "black.raspberries", displayName: "Black Raspberries",showImage: true },
{ shortName: "bleach", displayName: "Bleach",showImage: true },
{ shortName: "blood", displayName: "Blood",showImage: true },
{ shortName: "blue.berry", displayName: "Blue Berry",showImage: true },
{ shortName: "blueberries", displayName: "Blueberries",showImage: true },
{ shortName: "blueprintbase", displayName: "Blueprint",showImage: true },
{ shortName: "bone.armor.suit", displayName: "Bone Armor",showImage: true },
{ shortName: "bone.club", displayName: "Bone Club",showImage: true },
{ shortName: "bone.fragments", displayName: "Bone Fragments",showImage: true },
{ shortName: "boogieboard", displayName: "Boogie Board",showImage: true },
{ shortName: "boombox", displayName: "Boom Box",showImage: true },
{ shortName: "boots.frog", displayName: "Frog Boots",showImage: true },
{ shortName: "botabag", displayName: "Bota Bag",showImage: true },
{ shortName: "bow.compound", displayName: "Compound Bow",showImage: true },
{ shortName: "bow.hunting", displayName: "Hunting Bow",showImage: true },
{ shortName: "box.repair.bench", displayName: "Repair Bench",showImage: true },
{ shortName: "box.wooden", displayName: "Wood Storage Box",showImage: true },
{ shortName: "box.wooden.large", displayName: "Large Wood Box",showImage: true },
{ shortName: "bucket.helmet", displayName: "Bucket Helmet",showImage: true },
{ shortName: "bucket.water", displayName: "Water Bucket",showImage: true },
{ shortName: "building.planner", displayName: "Building Plan",showImage: true },
{ shortName: "burlap.gloves", displayName: "Leather Gloves",showImage: true },
{ shortName: "burlap.gloves.new", displayName: "Burlap Gloves",showImage: true },
{ shortName: "burlap.headwrap", displayName: "Burlap Headwrap",showImage: true },
{ shortName: "burlap.shirt", displayName: "Burlap Shirt",showImage: true },
{ shortName: "burlap.shoes", displayName: "Burlap Shoes",showImage: true },
{ shortName: "burlap.trousers", displayName: "Burlap Trousers",showImage: true },
{ shortName: "cactusflesh", displayName: "Cactus Flesh",showImage: true },
{ shortName: "cakefiveyear", displayName: "Birthday Cake",showImage: true },
{ shortName: "campfire", displayName: "Camp Fire",showImage: true },
{ shortName: "can.beans", displayName: "Can of Beans",showImage: true },
{ shortName: "can.beans.empty", displayName: "Empty Can Of Beans",showImage: true },
{ shortName: "can.tuna", displayName: "Can of Tuna",showImage: true },
{ shortName: "can.tuna.empty", displayName: "Empty Tuna Can",showImage: true },
{ shortName: "candycane", displayName: "Candy Cane",showImage: true },
{ shortName: "candycaneclub", displayName: "Candy Cane Club",showImage: true },
{ shortName: "car.key", displayName: "Car Key",showImage: true },
{ shortName: "carburetor1", displayName: "Low Quality Carburetor",showImage: true },
{ shortName: "carburetor2", displayName: "Medium Quality Carburetor",showImage: true },
{ shortName: "carburetor3", displayName: "High Quality Carburetor",showImage: true },
{ shortName: "cardtable", displayName: "Card Table",showImage: true },
{ shortName: "cassette", displayName: "Cassette - Long",showImage: true },
{ shortName: "cassette.medium", displayName: "Cassette - Medium",showImage: true },
{ shortName: "cassette.short", displayName: "Cassette - Short",showImage: true },
{ shortName: "cctv.camera", displayName: "CCTV Camera",showImage: true },
{ shortName: "ceilinglight", displayName: "Ceiling Light",showImage: true },
{ shortName: "chainsaw", displayName: "Chainsaw",showImage: true },
{ shortName: "chair", displayName: "Chair",showImage: true },
{ shortName: "charcoal", displayName: "Charcoal",showImage: true },
{ shortName: "chicken.burned", displayName: "Burnt Chicken",showImage: true },
{ shortName: "chicken.cooked", displayName: "Cooked Chicken",showImage: true },
{ shortName: "chicken.raw", displayName: "Raw Chicken Breast",showImage: true },
{ shortName: "chicken.spoiled", displayName: "Spoiled Chicken",showImage: true },
{ shortName: "chineselantern", displayName: "Chinese Lantern",showImage: true },
{ shortName: "chocholate", displayName: "Chocolate Bar",showImage: true },
{ shortName: "clatter.helmet", displayName: "Clatter Helmet",showImage: true },
{ shortName: "clone.black.berry", displayName: "Black Berry Clone",showImage: true },
{ shortName: "clone.blue.berry", displayName: "Blue Berry Clone",showImage: true },
{ shortName: "clone.corn", displayName: "Corn Clone",showImage: true },
{ shortName: "clone.green.berry", displayName: "Green Berry Clone",showImage: true },
{ shortName: "clone.hemp", displayName: "Hemp Clone",showImage: true },
{ shortName: "clone.potato", displayName: "Potato Clone",showImage: true },
{ shortName: "clone.pumpkin", displayName: "Pumpkin Plant Clone",showImage: true },
{ shortName: "clone.red.berry", displayName: "Red Berry Clone",showImage: true },
{ shortName: "clone.white.berry", displayName: "White Berry Clone",showImage: true },
{ shortName: "clone.yellow.berry", displayName: "Yellow Berry Clone",showImage: true },
{ shortName: "cloth", displayName: "Cloth",showImage: true },
{ shortName: "coal", displayName: "Coal :(",showImage: true },
{ shortName: "coffeecan.helmet", displayName: "Coffee Can Helmet",showImage: true },
{ shortName: "coffin.storage", displayName: "Coffin",showImage: true },
{ shortName: "composter", displayName: "Composter",showImage: true },
{ shortName: "computerstation", displayName: "Computer Station",showImage: true },
{ shortName: "connected.speaker", displayName: "Connected Speaker",showImage: true },
{ shortName: "corn", displayName: "Corn",showImage: true },
{ shortName: "crankshaft1", displayName: "Low Quality Crankshaft",showImage: true },
{ shortName: "crankshaft2", displayName: "Medium Quality Crankshaft",showImage: true },
{ shortName: "crankshaft3", displayName: "High Quality Crankshaft",showImage: true },
{ shortName: "cratecostume", displayName: "Crate Costume",showImage: true },
{ shortName: "crossbow", displayName: "Crossbow",showImage: true },
{ shortName: "crude.oil", displayName: "Crude Oil",showImage: true },
{ shortName: "cupboard.tool", displayName: "Tool Cupboard",showImage: true },
{ shortName: "cursedcauldron", displayName: "Cursed Cauldron",showImage: true },
{ shortName: "deer.skull.mask", displayName: "Bone Helmet",showImage: true },
{ shortName: "deermeat.burned", displayName: "Burnt Deer Meat",showImage: true },
{ shortName: "deermeat.cooked", displayName: "Cooked Deer Meat",showImage: true },
{ shortName: "deermeat.raw", displayName: "Raw Deer Meat",showImage: true },
{ shortName: "diesel_barrel", displayName: "Diesel Fuel",showImage: true },
{ shortName: "discoball", displayName: "Disco Ball",showImage: true },
{ shortName: "discofloor", displayName: "Disco Floor",showImage: true },
{ shortName: "discofloor.largetiles", displayName: "Disco Floor",showImage: true },
{ shortName: "diving.fins", displayName: "Diving Fins",showImage: true },
{ shortName: "diving.mask", displayName: "Diving Mask",showImage: true },
{ shortName: "diving.tank", displayName: "Diving Tank",showImage: true },
{ shortName: "diving.wetsuit", displayName: "Wetsuit",showImage: true },
{ shortName: "door.closer", displayName: "Door Closer",showImage: true },
{ shortName: "door.double.hinged.metal", displayName: "Sheet Metal Double Door",showImage: true },
{ shortName: "door.double.hinged.toptier", displayName: "Armored Double Door",showImage: true },
{ shortName: "door.double.hinged.wood", displayName: "Wood Double Door",showImage: true },
{ shortName: "door.hinged.industrial.a", displayName: "Industrial Door",showImage: true },
{ shortName: "door.hinged.metal", displayName: "Sheet Metal Door",showImage: true },
{ shortName: "door.hinged.toptier", displayName: "Armored Door",showImage: true },
{ shortName: "door.hinged.wood", displayName: "Wooden Door",showImage: true },
{ shortName: "door.key", displayName: "Door Key",showImage: true },
{ shortName: "dragondoorknocker", displayName: "Dragon Door Knocker",showImage: true },
{ shortName: "drone", displayName: "Drone",showImage: true },
{ shortName: "dropbox", displayName: "Drop Box",showImage: true },
{ shortName: "drumkit", displayName: "Junkyard Drum Kit",showImage: true },
{ shortName: "ducttape", displayName: "Duct Tape",showImage: true },
{ shortName: "easter.bronzeegg", displayName: "Bronze Egg",showImage: true },
{ shortName: "easter.goldegg", displayName: "Gold Egg",showImage: true },
{ shortName: "easter.paintedeggs", displayName: "Painted Egg",showImage: true },
{ shortName: "easter.silveregg", displayName: "Silver Egg",showImage: true },
{ shortName: "easterbasket", displayName: "Egg Basket",showImage: true },
{ shortName: "easterdoorwreath", displayName: "Easter Door Wreath",showImage: true },
{ shortName: "electric.andswitch", displayName: "AND Switch",showImage: true },
{ shortName: "electric.audioalarm", displayName: "Audio Alarm",showImage: true },
{ shortName: "electric.battery.rechargable.large", displayName: "Large Rechargeable Battery",showImage: true },
{ shortName: "electric.battery.rechargable.medium", displayName: "Medium Rechargeable Battery",showImage: true },
{ shortName: "electric.battery.rechargable.small", displayName: "Small Rechargeable Battery",showImage: true },
{ shortName: "electric.blocker", displayName: "Blocker",showImage: true },
{ shortName: "electric.button", displayName: "Button",showImage: true },
{ shortName: "electric.cabletunnel", displayName: "Cable Tunnel",showImage: true },
{ shortName: "electric.counter", displayName: "Counter",showImage: true },
{ shortName: "electric.doorcontroller", displayName: "Door Controller",showImage: true },
{ shortName: "electric.flasherlight", displayName: "Flasher Light",showImage: true },
{ shortName: "electric.fuelgenerator.small", displayName: "Small Generator",showImage: true },
{ shortName: "electric.generator.small", displayName: "Test Generator",showImage: true },
{ shortName: "electric.hbhfsensor", displayName: "HBHF Sensor",showImage: true },
{ shortName: "electric.heater", displayName: "Electric Heater",showImage: true },
{ shortName: "electric.igniter", displayName: "Igniter",showImage: true },
{ shortName: "electric.laserdetector", displayName: "Laser Detector",showImage: true },
{ shortName: "electric.orswitch", displayName: "OR Switch",showImage: true },
{ shortName: "electric.pressurepad", displayName: "Pressure Pad",showImage: true },
{ shortName: "electric.random.switch", displayName: "RAND Switch",showImage: true },
{ shortName: "electric.rf.broadcaster", displayName: "RF Broadcaster",showImage: true },
{ shortName: "electric.rf.receiver", displayName: "RF Receiver",showImage: true },
{ shortName: "electric.simplelight", displayName: "Simple Light",showImage: true },
{ shortName: "electric.sirenlight", displayName: "Siren Light",showImage: true },
{ shortName: "electric.solarpanel.large", displayName: "Large Solar Panel",showImage: true },
{ shortName: "electric.splitter", displayName: "Splitter",showImage: true },
{ shortName: "electric.sprinkler", displayName: "Sprinkler",showImage: true },
{ shortName: "electric.switch", displayName: "Switch",showImage: true },
{ shortName: "electric.teslacoil", displayName: "Tesla Coil",showImage: true },
{ shortName: "electric.timer", displayName: "Timer",showImage: true },
{ shortName: "electric.xorswitch", displayName: "XOR Switch",showImage: true },
{ shortName: "electrical.branch", displayName: "Electrical Branch",showImage: true },
{ shortName: "electrical.combiner", displayName: "Root Combiner",showImage: true },
{ shortName: "electrical.memorycell", displayName: "Memory Cell",showImage: true },
{ shortName: "elevator", displayName: "Elevator",showImage: true },
{ shortName: "explosive.satchel", displayName: "Satchel Charge",showImage: true },
{ shortName: "explosive.timed", displayName: "Timed Explosive Charge",showImage: true },
{ shortName: "explosives", displayName: "Explosives",showImage: true },
{ shortName: "fat.animal", displayName: "Animal Fat",showImage: true },
{ shortName: "fertilizer", displayName: "Fertilizer",showImage: true },
{ shortName: "fireplace.stone", displayName: "Stone Fireplace",showImage: true },
{ shortName: "firework.boomer.blue", displayName: "Blue Boomer",showImage: true },
{ shortName: "firework.boomer.champagne", displayName: "Champagne Boomer",showImage: true },
{ shortName: "firework.boomer.green", displayName: "Green Boomer",showImage: true },
{ shortName: "firework.boomer.orange", displayName: "Orange Boomer",showImage: true },
{ shortName: "firework.boomer.red", displayName: "Red Boomer",showImage: true },
{ shortName: "firework.boomer.violet", displayName: "Violet Boomer",showImage: true },
{ shortName: "firework.romancandle.blue", displayName: "Blue Roman Candle",showImage: true },
{ shortName: "firework.romancandle.green", displayName: "Green Roman Candle",showImage: true },
{ shortName: "firework.romancandle.red", displayName: "Red Roman Candle",showImage: true },
{ shortName: "firework.romancandle.violet", displayName: "Violet Roman Candle",showImage: true },
{ shortName: "firework.volcano", displayName: "White Volcano Firework",showImage: true },
{ shortName: "firework.volcano.red", displayName: "Red Volcano Firework",showImage: true },
{ shortName: "firework.volcano.violet", displayName: "Violet Volcano Firework",showImage: true },
{ shortName: "fish.anchovy", displayName: "Anchovy",showImage: true },
{ shortName: "fish.catfish", displayName: "Catfish",showImage: true },
{ shortName: "fish.cooked", displayName: "Cooked Fish",showImage: true },
{ shortName: "fish.herring", displayName: "Herring",showImage: true },
{ shortName: "fish.minnows", displayName: "Minnows",showImage: true },
{ shortName: "fish.orangeroughy", displayName: "Orange Roughy",showImage: true },
{ shortName: "fish.raw", displayName: "Raw Fish",showImage: true },
{ shortName: "fish.salmon", displayName: "Salmon",showImage: true },
{ shortName: "fish.sardine", displayName: "Sardine",showImage: true },
{ shortName: "fish.smallshark", displayName: "Small Shark",showImage: true },
{ shortName: "fish.troutsmall", displayName: "Small Trout",showImage: true },
{ shortName: "fish.yellowperch", displayName: "Yellow Perch",showImage: true },
{ shortName: "fishingrod.handmade", displayName: "Handmade Fishing Rod",showImage: true },
{ shortName: "fishtrap.small", displayName: "Survival Fish Trap",showImage: true },
{ shortName: "flamethrower", displayName: "Flame Thrower",showImage: true },
{ shortName: "flameturret", displayName: "Flame Turret",showImage: true },
{ shortName: "flare", displayName: "Flare",showImage: true },
{ shortName: "flashlight.held", displayName: "Flashlight",showImage: true },
{ shortName: "floor.grill", displayName: "Floor grill",showImage: true },
{ shortName: "floor.ladder.hatch", displayName: "Ladder Hatch",showImage: true },
{ shortName: "floor.triangle.grill", displayName: "Floor triangle grill",showImage: true },
{ shortName: "floor.triangle.ladder.hatch", displayName: "Triangle Ladder Hatch",showImage: true },
{ shortName: "fluid.combiner", displayName: "Fluid Combiner",showImage: true },
{ shortName: "fluid.splitter", displayName: "Fluid Splitter",showImage: true },
{ shortName: "fluid.switch", displayName: "Fluid Switch & Pump",showImage: true },
{ shortName: "fogmachine", displayName: "Fogger-3000",showImage: true },
{ shortName: "fridge", displayName: "Fridge",showImage: true },
{ shortName: "fun.bass", displayName: "Shovel Bass",showImage: true },
{ shortName: "fun.boomboxportable", displayName: "Portable Boom Box",showImage: true },
{ shortName: "fun.casetterecorder", displayName: "Cassette Recorder",showImage: true },
{ shortName: "fun.cowbell", displayName: "Cowbell",showImage: true },
{ shortName: "fun.flute", displayName: "Pan Flute",showImage: true },
{ shortName: "fun.guitar", displayName: "Acoustic Guitar",showImage: true },
{ shortName: "fun.jerrycanguitar", displayName: "Jerry Can Guitar",showImage: true },
{ shortName: "fun.tambourine", displayName: "Canbourine",showImage: true },
{ shortName: "fun.trumpet", displayName: "Plumber's Trumpet",showImage: true },
{ shortName: "fun.tuba", displayName: "Sousaphone",showImage: true },
{ shortName: "furnace", displayName: "Furnace",showImage: true },
{ shortName: "furnace.large", displayName: "Large Furnace",showImage: true },
{ shortName: "fuse", displayName: "Electric Fuse",showImage: true },
{ shortName: "gates.external.high.stone", displayName: "High External Stone Gate",showImage: true },
{ shortName: "gates.external.high.wood", displayName: "High External Wooden Gate",showImage: true },
{ shortName: "gears", displayName: "Gears",showImage: true },
{ shortName: "geiger.counter", displayName: "Geiger Counter",showImage: true },
{ shortName: "generator.wind.scrap", displayName: "Wind Turbine",showImage: true },
{ shortName: "ghostsheet", displayName: "Ghost Costume",showImage: true },
{ shortName: "giantcandycanedecor", displayName: "Giant Candy Decor",showImage: true },
{ shortName: "giantlollipops", displayName: "Giant Lollipop Decor",showImage: true },
{ shortName: "gloweyes", displayName: "Glowing Eyes",showImage: true },
{ shortName: "glue", displayName: "Glue",showImage: true },
{ shortName: "granolabar", displayName: "Granola Bar",showImage: true },
{ shortName: "gravestone", displayName: "Gravestone",showImage: true },
{ shortName: "green.berry", displayName: "Green Berry",showImage: true },
{ shortName: "grenade.beancan", displayName: "Beancan Grenade",showImage: true },
{ shortName: "grenade.f1", displayName: "F1 Grenade",showImage: true },
{ shortName: "grenade.smoke", displayName: "Smoke Grenade",showImage: true },
{ shortName: "grub", displayName: "Grub",showImage: true },
{ shortName: "gun.water", displayName: "Water Gun",showImage: true },
{ shortName: "gunpowder", displayName: "Gun Powder",showImage: true },
{ shortName: "guntrap", displayName: "Shotgun Trap",showImage: true },
{ shortName: "habrepair", displayName: "Hab Repair",showImage: true },
{ shortName: "halloween.candy", displayName: "Halloween Candy",showImage: true },
{ shortName: "halloween.lootbag.large", displayName: "Large Loot Bag",showImage: true },
{ shortName: "halloween.lootbag.medium", displayName: "Medium Loot Bag",showImage: true },
{ shortName: "halloween.lootbag.small", displayName: "Small Loot Bag",showImage: true },
{ shortName: "halloween.mummysuit", displayName: "Mummy Suit",showImage: true },
{ shortName: "halloween.surgeonsuit", displayName: "Surgeon Scrubs",showImage: true },
{ shortName: "hammer", displayName: "Hammer",showImage: true },
{ shortName: "hammer.salvaged", displayName: "Salvaged Hammer",showImage: true },
{ shortName: "hat.beenie", displayName: "Beenie Hat",showImage: true },
{ shortName: "hat.boonie", displayName: "Boonie Hat",showImage: true },
{ shortName: "hat.bunnyhat", displayName: "Bunny Hat",showImage: true },
{ shortName: "hat.candle", displayName: "Candle Hat",showImage: true },
{ shortName: "hat.cap", displayName: "Baseball Cap",showImage: true },
{ shortName: "hat.dragonmask", displayName: "Dragon Mask",showImage: true },
{ shortName: "hat.gas.mask", displayName: "Gas Mask",showImage: true },
{ shortName: "hat.miner", displayName: "Miners Hat",showImage: true },
{ shortName: "hat.oxmask", displayName: "Ox Mask",showImage: true },
{ shortName: "hat.ratmask", displayName: "Rat Mask",showImage: true },
{ shortName: "hat.wolf", displayName: "Wolf Headdress",showImage: true },
{ shortName: "hatchet", displayName: "Hatchet",showImage: true },
{ shortName: "hazmatsuit", displayName: "Hazmat Suit",showImage: true },
{ shortName: "hazmatsuit.spacesuit", displayName: "Space Suit",showImage: true },
{ shortName: "hazmatsuit_scientist", displayName: "Scientist Suit",showImage: true },
{ shortName: "hazmatsuit_scientist_peacekeeper", displayName: "Scientist Suit",showImage: true },
{ shortName: "healingtea", displayName: "Basic Healing Tea",showImage: true },
{ shortName: "healingtea.advanced", displayName: "Advanced Healing Tea",showImage: true },
{ shortName: "healingtea.pure", displayName: "Pure Healing Tea",showImage: true },
{ shortName: "heavy.plate.helmet", displayName: "Heavy Plate Helmet",showImage: true },
{ shortName: "heavy.plate.jacket", displayName: "Heavy Plate Jacket",showImage: true },
{ shortName: "heavy.plate.pants", displayName: "Heavy Plate Pants",showImage: true },
{ shortName: "hitchtroughcombo", displayName: "Hitch & Trough",showImage: true },
{ shortName: "hobobarrel", displayName: "Hobo Barrel",showImage: true },
{ shortName: "hoodie", displayName: "Hoodie",showImage: true },
{ shortName: "horse.armor.roadsign", displayName: "Roadsign Horse Armor",showImage: true },
{ shortName: "horse.armor.wood", displayName: "Wooden Horse Armor",showImage: true },
{ shortName: "horse.saddle", displayName: "Horse Saddle",showImage: true },
{ shortName: "horse.saddlebag", displayName: "Saddle bag",showImage: true },
{ shortName: "horse.shoes.advanced", displayName: "High Quality Horse Shoes",showImage: true },
{ shortName: "horse.shoes.basic", displayName: "Basic Horse Shoes",showImage: true },
{ shortName: "horsedung", displayName: "Horse Dung",showImage: true },
{ shortName: "horsemeat.burned", displayName: "Burnt Horse Meat",showImage: true },
{ shortName: "horsemeat.cooked", displayName: "Cooked Horse Meat",showImage: true },
{ shortName: "horsemeat.raw", displayName: "Raw Horse Meat",showImage: true },
{ shortName: "hosetool", displayName: "Hose Tool",showImage: true },
{ shortName: "hq.metal.ore", displayName: "High Quality Metal Ore",showImage: true },
{ shortName: "humanmeat.burned", displayName: "Burnt Human Meat",showImage: true },
{ shortName: "humanmeat.cooked", displayName: "Cooked Human Meat",showImage: true },
{ shortName: "humanmeat.raw", displayName: "Raw Human Meat",showImage: true },
{ shortName: "humanmeat.spoiled", displayName: "Spoiled Human Meat",showImage: true },
{ shortName: "icepick.salvaged", displayName: "Salvaged Icepick",showImage: true },
{ shortName: "innertube", displayName: "Inner Tube",showImage: true },
{ shortName: "innertube.horse", displayName: "Inner Tube",showImage: true },
{ shortName: "innertube.unicorn", displayName: "Inner Tube",showImage: true },
{ shortName: "jacket", displayName: "Jacket",showImage: true },
{ shortName: "jacket.snow", displayName: "Snow Jacket",showImage: true },
{ shortName: "jackhammer", displayName: "Jackhammer",showImage: true },
{ shortName: "jackolantern.angry", displayName: "Jack O Lantern Angry",showImage: true },
{ shortName: "jackolantern.happy", displayName: "Jack O Lantern Happy",showImage: true },
{ shortName: "jar.pickle", displayName: "Pickles",showImage: true },
{ shortName: "jumpsuit.suit", displayName: "Jumpsuit",showImage: true },
{ shortName: "jumpsuit.suit.blue", displayName: "Blue Jumpsuit",showImage: true },
{ shortName: "kayak", displayName: "Kayak",showImage: true },
{ shortName: "keycard_blue", displayName: "Blue Keycard",showImage: true },
{ shortName: "keycard_green", displayName: "Green Keycard",showImage: true },
{ shortName: "keycard_red", displayName: "Red Keycard",showImage: true },
{ shortName: "knife.bone", displayName: "Bone Knife",showImage: true },
{ shortName: "knife.butcher", displayName: "Butcher Knife",showImage: true },
{ shortName: "knife.combat", displayName: "Combat Knife",showImage: true },
{ shortName: "ladder.wooden.wall", displayName: "Wooden Ladder",showImage: true },
{ shortName: "lantern", displayName: "Lantern",showImage: true },
{ shortName: "largecandles", displayName: "Large Candle Set",showImage: true },
{ shortName: "largemedkit", displayName: "Large Medkit",showImage: true },
{ shortName: "laserlight", displayName: "Laser Light",showImage: true },
{ shortName: "leather", displayName: "Leather",showImage: true },
{ shortName: "lmg.m249", displayName: "M249",showImage: true },
{ shortName: "lock.code", displayName: "Code Lock",showImage: true },
{ shortName: "lock.key", displayName: "Key Lock",showImage: true },
{ shortName: "locker", displayName: "Locker",showImage: true },
{ shortName: "longsword", displayName: "Longsword",showImage: true },
{ shortName: "lowgradefuel", displayName: "Low Grade Fuel",showImage: true },
{ shortName: "lunar.firecrackers", displayName: "Firecracker String",showImage: true },
{ shortName: "mace", displayName: "Mace",showImage: true },
{ shortName: "machete", displayName: "Machete",showImage: true },
{ shortName: "mailbox", displayName: "Mail Box",showImage: true },
{ shortName: "map", displayName: "Paper Map",showImage: true },
{ shortName: "mask.balaclava", displayName: "Improvised Balaclava",showImage: true },
{ shortName: "mask.bandana", displayName: "Bandana Mask",showImage: true },
{ shortName: "maxhealthtea", displayName: "Basic Max Health Tea",showImage: true },
{ shortName: "maxhealthtea.advanced", displayName: "Advanced Max Health Tea",showImage: true },
{ shortName: "maxhealthtea.pure", displayName: "Pure Max Health Tea",showImage: true },
{ shortName: "meat.boar", displayName: "Raw Pork",showImage: true },
{ shortName: "meat.pork.burned", displayName: "Burnt Pork",showImage: true },
{ shortName: "meat.pork.cooked", displayName: "Cooked Pork",showImage: true },
{ shortName: "megaphone", displayName: "Megaphone",showImage: true },
{ shortName: "metal.facemask", displayName: "Metal Facemask",showImage: true },
{ shortName: "metal.fragments", displayName: "Metal Fragments",showImage: true },
{ shortName: "metal.ore", displayName: "Metal Ore",showImage: true },
{ shortName: "metal.plate.torso", displayName: "Metal Chest Plate",showImage: true },
{ shortName: "metal.refined", displayName: "High Quality Metal",showImage: true },
{ shortName: "metalblade", displayName: "Metal Blade",showImage: true },
{ shortName: "metalpipe", displayName: "Metal Pipe",showImage: true },
{ shortName: "metalspring", displayName: "Metal Spring",showImage: true },
{ shortName: "microphonestand", displayName: "Microphone Stand",showImage: true },
{ shortName: "minihelicopter.repair", displayName: "MC repair",showImage: true },
{ shortName: "mining.pumpjack", displayName: "Pump Jack",showImage: true },
{ shortName: "mining.quarry", displayName: "Mining Quarry",showImage: true },
{ shortName: "mixingtable", displayName: "Mixing Table",showImage: true },
{ shortName: "mobilephone", displayName: "Mobile Phone",showImage: true },
{ shortName: "modularcarlift", displayName: "Modular Car Lift",showImage: true },
{ shortName: "movembermoustache", displayName: "Movember Moustache",showImage: true },
{ shortName: "movembermoustachecard", displayName: "Card Movember Moustache",showImage: true },
{ shortName: "multiplegrenadelauncher", displayName: "Multiple Grenade Launcher",showImage: true },
{ shortName: "mushroom", displayName: "Mushroom",showImage: true },
{ shortName: "newyeargong", displayName: "New Year Gong",showImage: true },
{ shortName: "nightvisiongoggles", displayName: "Night Vision Goggles",showImage: true },
{ shortName: "note", displayName: "Note",showImage: true },
{ shortName: "oretea", displayName: "Basic Ore Tea",showImage: true },
{ shortName: "oretea.advanced", displayName: "Advanced Ore Tea",showImage: true },
{ shortName: "oretea.pure", displayName: "Pure Ore Tea",showImage: true },
{ shortName: "paddle", displayName: "Paddle",showImage: true },
{ shortName: "paddlingpool", displayName: "Paddling Pool",showImage: true },
{ shortName: "pants", displayName: "Pants",showImage: true },
{ shortName: "pants.shorts", displayName: "Shorts",showImage: true },
{ shortName: "paper", displayName: "Paper",showImage: true },
{ shortName: "partyhat", displayName: "Party Hat",showImage: true },
{ shortName: "photo", displayName: "Photograph",showImage: true },
{ shortName: "photoframe.landscape", displayName: "Landscape Photo Frame",showImage: true },
{ shortName: "photoframe.large", displayName: "Large Photo Frame",showImage: true },
{ shortName: "photoframe.portrait", displayName: "Portrait Photo Frame",showImage: true },
{ shortName: "piano", displayName: "Wheelbarrow Piano",showImage: true },
{ shortName: "pickaxe", displayName: "Pickaxe",showImage: true },
{ shortName: "pistol.eoka", displayName: "Eoka Pistol",showImage: true },
{ shortName: "pistol.m92", displayName: "M92 Pistol",showImage: true },
{ shortName: "pistol.nailgun", displayName: "Nailgun",showImage: true },
{ shortName: "pistol.python", displayName: "Python Revolver",showImage: true },
{ shortName: "pistol.revolver", displayName: "Revolver",showImage: true },
{ shortName: "pistol.semiauto", displayName: "Semi-Automatic Pistol",showImage: true },
{ shortName: "pistol.water", displayName: "Water Pistol",showImage: true },
{ shortName: "piston1", displayName: "Low Quality Pistons",showImage: true },
{ shortName: "piston2", displayName: "Medium Quality Pistons",showImage: true },
{ shortName: "piston3", displayName: "High Quality Pistons",showImage: true },
{ shortName: "pitchfork", displayName: "Pitchfork",showImage: true },
{ shortName: "planter.large", displayName: "Large Planter Box",showImage: true },
{ shortName: "planter.small", displayName: "Small Planter Box",showImage: true },
{ shortName: "plantfiber", displayName: "Plant Fiber",showImage: true },
{ shortName: "pookie.bear", displayName: "Pookie Bear",showImage: true },
{ shortName: "potato", displayName: "Potato",showImage: true },
{ shortName: "powered.water.purifier", displayName: "Powered Water Purifier",showImage: true },
{ shortName: "propanetank", displayName: "Empty Propane Tank",showImage: true },
{ shortName: "pumpkin", displayName: "Pumpkin",showImage: true },
{ shortName: "pumpkinbasket", displayName: "Pumpkin Bucket",showImage: true },
{ shortName: "radiationremovetea", displayName: "Rad. Removal Tea",showImage: true },
{ shortName: "radiationremovetea.advanced", displayName: "Advanced Rad. Removal Tea",showImage: true },
{ shortName: "radiationremovetea.pure", displayName: "Pure Rad. Removal Tea",showImage: true },
{ shortName: "radiationresisttea", displayName: "Anti-Rad Tea",showImage: true },
{ shortName: "radiationresisttea.advanced", displayName: "Adv. Anti-Rad Tea",showImage: true },
{ shortName: "radiationresisttea.pure", displayName: "Pure Anti-Rad Tea",showImage: true },
{ shortName: "red.berry", displayName: "Red Berry",showImage: true },
{ shortName: "research.table", displayName: "Research Table",showImage: true },
{ shortName: "researchpaper", displayName: "Research Paper",showImage: true },
{ shortName: "rf.detonator", displayName: "RF Transmitter",showImage: true },
{ shortName: "rf_pager", displayName: "RF Pager",showImage: true },
{ shortName: "rifle.ak", displayName: "Assault Rifle",showImage: true },
{ shortName: "rifle.bolt", displayName: "Bolt Action Rifle",showImage: true },
{ shortName: "rifle.l96", displayName: "L96 Rifle",showImage: true },
{ shortName: "rifle.lr300", displayName: "LR-300 Assault Rifle",showImage: true },
{ shortName: "rifle.m39", displayName: "M39 Rifle",showImage: true },
{ shortName: "rifle.semiauto", displayName: "Semi-Automatic Rifle",showImage: true },
{ shortName: "riflebody", displayName: "Rifle Body",showImage: true },
{ shortName: "riot.helmet", displayName: "Riot Helmet",showImage: true },
{ shortName: "roadsign.gloves", displayName: "Roadsign Gloves",showImage: true },
{ shortName: "roadsign.jacket", displayName: "Road Sign Jacket",showImage: true },
{ shortName: "roadsign.kilt", displayName: "Road Sign Kilt",showImage: true },
{ shortName: "roadsigns", displayName: "Road Signs",showImage: true },
{ shortName: "rock", displayName: "Rock",showImage: true },
{ shortName: "rocket.launcher", displayName: "Rocket Launcher",showImage: true },
{ shortName: "rope", displayName: "Rope",showImage: true },
{ shortName: "rug", displayName: "Rug",showImage: true },
{ shortName: "rug.bear", displayName: "Rug Bear Skin",showImage: true },
{ shortName: "rustige_egg_a", displayName: "Rustigé Egg - Red",showImage: true },
{ shortName: "rustige_egg_b", displayName: "Rustigé Egg - Blue",showImage: true },
{ shortName: "rustige_egg_c", displayName: "Rustigé Egg - Purple",showImage: true },
{ shortName: "rustige_egg_d", displayName: "Rustigé Egg - Ivory",showImage: true },
{ shortName: "rustige_egg_e", displayName: "Rustigé Egg - Green",showImage: true },
{ shortName: "salvaged.cleaver", displayName: "Salvaged Cleaver",showImage: true },
{ shortName: "salvaged.sword", displayName: "Salvaged Sword",showImage: true },
{ shortName: "samsite", displayName: "SAM Site",showImage: true },
{ shortName: "santabeard", displayName: "Santa Beard",showImage: true },
{ shortName: "santahat", displayName: "Santa Hat",showImage: true },
{ shortName: "scarecrow", displayName: "Scarecrow",showImage: true },
{ shortName: "scarecrow.suit", displayName: "Scarecrow Suit",showImage: true },
{ shortName: "scarecrowhead", displayName: "Scarecrow Wrap",showImage: true },
{ shortName: "scientistsuit_heavy", displayName: "Heavy Scientist Suit",showImage: true },
{ shortName: "scrap", displayName: "Scrap",showImage: true },
{ shortName: "scraptea", displayName: "Basic Scrap Tea",showImage: true },
{ shortName: "scraptea.advanced", displayName: "Advanced Scrap Tea",showImage: true },
{ shortName: "scraptea.pure", displayName: "Pure Scrap Tea",showImage: true },
{ shortName: "scraptransportheli.repair", displayName: "ScrapTransportHeliRepair",showImage: true },
{ shortName: "searchlight", displayName: "Search Light",showImage: true },
{ shortName: "secretlabchair", displayName: "Secret Lab Chair",showImage: true },
{ shortName: "seed.black.berry", displayName: "Black Berry Seed",showImage: true },
{ shortName: "seed.blue.berry", displayName: "Blue Berry Seed",showImage: true },
{ shortName: "seed.corn", displayName: "Corn Seed",showImage: true },
{ shortName: "seed.green.berry", displayName: "Green Berry Seed",showImage: true },
{ shortName: "seed.hemp", displayName: "Hemp Seed",showImage: true },
{ shortName: "seed.potato", displayName: "Potato Seed",showImage: true },
{ shortName: "seed.pumpkin", displayName: "Pumpkin Seed",showImage: true },
{ shortName: "seed.red.berry", displayName: "Red Berry Seed",showImage: true },
{ shortName: "seed.white.berry", displayName: "White Berry Seed",showImage: true },
{ shortName: "seed.yellow.berry", displayName: "Yellow Berry Seed",showImage: true },
{ shortName: "semibody", displayName: "Semi Automatic Body",showImage: true },
{ shortName: "sewingkit", displayName: "Sewing Kit",showImage: true },
{ shortName: "sheetmetal", displayName: "Sheet Metal",showImage: true },
{ shortName: "shelves", displayName: "Salvaged Shelves",showImage: true },
{ shortName: "shirt.collared", displayName: "Shirt",showImage: true },
{ shortName: "shirt.tanktop", displayName: "Tank Top",showImage: true },
{ shortName: "shoes.boots", displayName: "Boots",showImage: true },
{ shortName: "shotgun.double", displayName: "Double Barrel Shotgun",showImage: true },
{ shortName: "shotgun.pump", displayName: "Pump Shotgun",showImage: true },
{ shortName: "shotgun.spas12", displayName: "Spas-12 Shotgun",showImage: true },
{ shortName: "shotgun.waterpipe", displayName: "Waterpipe Shotgun",showImage: true },
{ shortName: "shutter.metal.embrasure.a", displayName: "Metal horizontal embrasure",showImage: true },
{ shortName: "shutter.metal.embrasure.b", displayName: "Metal Vertical embrasure",showImage: true },
{ shortName: "shutter.wood.a", displayName: "Wood Shutters",showImage: true },
{ shortName: "sickle", displayName: "Sickle",showImage: true },
{ shortName: "sign.hanging", displayName: "Two Sided Hanging Sign",showImage: true },
{ shortName: "sign.hanging.banner.large", displayName: "Large Banner Hanging",showImage: true },
{ shortName: "sign.hanging.ornate", displayName: "Two Sided Ornate Hanging Sign",showImage: true },
{ shortName: "sign.neon.125x125", displayName: "Small Neon Sign",showImage: true },
{ shortName: "sign.neon.125x215", displayName: "Medium Neon Sign",showImage: true },
{ shortName: "sign.neon.125x215.animated", displayName: "Medium Animated Neon Sign",showImage: true },
{ shortName: "sign.neon.xl", displayName: "Large Neon Sign",showImage: true },
{ shortName: "sign.neon.xl.animated", displayName: "Large Animated Neon Sign",showImage: true },
{ shortName: "sign.pictureframe.landscape", displayName: "Landscape Picture Frame",showImage: true },
{ shortName: "sign.pictureframe.portrait", displayName: "Portrait Picture Frame",showImage: true },
{ shortName: "sign.pictureframe.tall", displayName: "Tall Picture Frame",showImage: true },
{ shortName: "sign.pictureframe.xl", displayName: "XL Picture Frame",showImage: true },
{ shortName: "sign.pictureframe.xxl", displayName: "XXL Picture Frame",showImage: true },
{ shortName: "sign.pole.banner.large", displayName: "Large Banner on pole",showImage: true },
{ shortName: "sign.post.double", displayName: "Double Sign Post",showImage: true },
{ shortName: "sign.post.single", displayName: "Single Sign Post",showImage: true },
{ shortName: "sign.post.town", displayName: "One Sided Town Sign Post",showImage: true },
{ shortName: "sign.post.town.roof", displayName: "Two Sided Town Sign Post",showImage: true },
{ shortName: "sign.wooden.huge", displayName: "Huge Wooden Sign",showImage: true },
{ shortName: "sign.wooden.large", displayName: "Large Wooden Sign",showImage: true },
{ shortName: "sign.wooden.medium", displayName: "Medium Wooden Sign",showImage: true },
{ shortName: "sign.wooden.small", displayName: "Small Wooden Sign",showImage: true },
{ shortName: "skull.human", displayName: "Human Skull",showImage: true },
{ shortName: "skull.trophy", displayName: "Skull Trophy",showImage: true },
{ shortName: "skull.trophy.jar", displayName: "Skull Trophy",showImage: true },
{ shortName: "skull.trophy.jar2", displayName: "Skull Trophy",showImage: true },
{ shortName: "skull.trophy.table", displayName: "Skull Trophy",showImage: true },
{ shortName: "skull.wolf", displayName: "Wolf Skull",showImage: true },
{ shortName: "skull_fire_pit", displayName: "Skull Fire Pit",showImage: true },
{ shortName: "skulldoorknocker", displayName: "Skull Door Knocker",showImage: true },
{ shortName: "skullspikes", displayName: "Skull Spikes",showImage: true },
{ shortName: "skullspikes.candles", displayName: "Skull Spikes",showImage: true },
{ shortName: "skullspikes.pumpkin", displayName: "Skull Spikes",showImage: true },
{ shortName: "sled", displayName: "Sled",showImage: true },
{ shortName: "sled.xmas", displayName: "Sled",showImage: true },
{ shortName: "sleepingbag", displayName: "Sleeping Bag",showImage: true },
{ shortName: "small.oil.refinery", displayName: "Small Oil Refinery",showImage: true },
{ shortName: "smallcandles", displayName: "Small Candle Set",showImage: true },
{ shortName: "smallwaterbottle", displayName: "Small Water Bottle",showImage: true },
{ shortName: "smart.alarm", displayName: "Smart Alarm",showImage: true },
{ shortName: "smart.switch", displayName: "Smart Switch",showImage: true },
{ shortName: "smg.2", displayName: "Custom SMG",showImage: true },
{ shortName: "smg.mp5", displayName: "MP5A4",showImage: true },
{ shortName: "smg.thompson", displayName: "Thompson",showImage: true },
{ shortName: "smgbody", displayName: "SMG Body",showImage: true },
{ shortName: "snowball", displayName: "Snowball",showImage: true },
{ shortName: "snowballgun", displayName: "Snowball Gun",showImage: true },
{ shortName: "snowmachine", displayName: "Snow Machine",showImage: true },
{ shortName: "snowman", displayName: "Snowman",showImage: true },
{ shortName: "sofa", displayName: "Sofa",showImage: true },
{ shortName: "soundlight", displayName: "Sound Light",showImage: true },
{ shortName: "sparkplug1", displayName: "Low Quality Spark Plugs",showImage: true },
{ shortName: "sparkplug2", displayName: "Medium Quality Spark Plugs",showImage: true },
{ shortName: "sparkplug3", displayName: "High Quality Spark Plugs",showImage: true },
{ shortName: "spear.stone", displayName: "Stone Spear",showImage: true },
{ shortName: "spear.wooden", displayName: "Wooden Spear",showImage: true },
{ shortName: "speargun", displayName: "Speargun",showImage: true },
{ shortName: "speargun.spear", displayName: "Speargun Spear",showImage: true },
{ shortName: "spiderweb", displayName: "Spider Webs",showImage: true },
{ shortName: "spikes.floor", displayName: "Wooden Floor Spikes",showImage: true },
{ shortName: "spinner.wheel", displayName: "Spinning wheel",showImage: true },
{ shortName: "spookyspeaker", displayName: "Spooky Speaker",showImage: true },
{ shortName: "stash.small", displayName: "Small Stash",showImage: true },
{ shortName: "sticks", displayName: "Sticks",showImage: true },
{ shortName: "stocking.large", displayName: "SUPER Stocking",showImage: true },
{ shortName: "stocking.small", displayName: "Small Stocking",showImage: true },
{ shortName: "stone.pickaxe", displayName: "Stone Pickaxe",showImage: true },
{ shortName: "stonehatchet", displayName: "Stone Hatchet",showImage: true },
{ shortName: "stones", displayName: "Stones",showImage: true },
{ shortName: "storage.monitor", displayName: "Storage Monitor",showImage: true },
{ shortName: "strobelight", displayName: "Strobe Light",showImage: true },
{ shortName: "submarine.torpedo.rising", displayName: "Surface torpedo",showImage: true },
{ shortName: "submarine.torpedo.straight", displayName: "Direct Torpedo",showImage: true },
{ shortName: "submarineduo", displayName: "Duo Submarine",showImage: true },
{ shortName: "submarinesolo", displayName: "Solo Submarine",showImage: true },
{ shortName: "sulfur", displayName: "Sulfur",showImage: true },
{ shortName: "sulfur.ore", displayName: "Sulfur Ore",showImage: true },
{ shortName: "sunglasses", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses02black", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses02camo", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses02red", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses03black", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses03chrome", displayName: "Sunglasses",showImage: true },
{ shortName: "sunglasses03gold", displayName: "Sunglasses",showImage: true },
{ shortName: "supply.signal", displayName: "Supply Signal",showImage: true },
{ shortName: "surveycharge", displayName: "Survey Charge",showImage: true },
{ shortName: "syringe.medical", displayName: "Medical Syringe",showImage: true },
{ shortName: "table", displayName: "Table",showImage: true },
{ shortName: "tactical.gloves", displayName: "Tactical Gloves",showImage: true },
{ shortName: "target.reactive", displayName: "Reactive Target",showImage: true },
{ shortName: "targeting.computer", displayName: "Targeting Computer",showImage: true },
{ shortName: "tarp", displayName: "Tarp",showImage: true },
{ shortName: "techparts", displayName: "Tech Trash",showImage: true },
{ shortName: "telephone", displayName: "Telephone",showImage: true },
{ shortName: "tool.binoculars", displayName: "Binoculars",showImage: true },
{ shortName: "tool.camera", displayName: "Camera",showImage: true },
{ shortName: "tool.instant_camera", displayName: "Instant Camera",showImage: true },
{ shortName: "toolgun", displayName: "Garry's Mod Tool Gun",showImage: true },
{ shortName: "torch", displayName: "Torch",showImage: true },
{ shortName: "trap.bear", displayName: "Snap Trap",showImage: true },
{ shortName: "trap.landmine", displayName: "Land Mine",showImage: true },
{ shortName: "tshirt", displayName: "T-Shirt",showImage: true },
{ shortName: "tshirt.long", displayName: "Longsleeve T-Shirt",showImage: true },
{ shortName: "tunalight", displayName: "Tuna Can Lamp",showImage: true },
{ shortName: "twitch.headset", displayName: "Headset",showImage: true },
{ shortName: "twitchsunglasses", displayName: "Purple Sunglasses",showImage: true },
{ shortName: "valve1", displayName: "Low Quality Valves",showImage: true },
{ shortName: "valve2", displayName: "Medium Quality Valves",showImage: true },
{ shortName: "valve3", displayName: "High Quality Valves",showImage: true },
{ shortName: "vehicle.1mod.cockpit", displayName: "Cockpit Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.cockpit.armored", displayName: "Armored Cockpit Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.cockpit.with.engine", displayName: "Cockpit With Engine Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.engine", displayName: "Engine Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.flatbed", displayName: "Flatbed Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.passengers.armored", displayName: "Armored Passenger Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.rear.seats", displayName: "Rear Seats Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.storage", displayName: "Storage Vehicle Module",showImage: true },
{ shortName: "vehicle.1mod.taxi", displayName: "Taxi Vehicle Module",showImage: true },
{ shortName: "vehicle.2mod.flatbed", displayName: "Large Flatbed Vehicle Module",showImage: true },
{ shortName: "vehicle.2mod.fuel.tank", displayName: "Fuel Tank Vehicle Module",showImage: true },
{ shortName: "vehicle.2mod.passengers", displayName: "Passenger Vehicle Module",showImage: true },
{ shortName: "vehicle.chassis", displayName: "Generic vehicle chassis",showImage: true },
{ shortName: "vehicle.chassis.2mod", displayName: "Small Chassis",showImage: true },
{ shortName: "vehicle.chassis.3mod", displayName: "Medium Chassis",showImage: true },
{ shortName: "vehicle.chassis.4mod", displayName: "Large Chassis",showImage: true },
{ shortName: "vehicle.module", displayName: "Generic vehicle module",showImage: true },
{ shortName: "vending.machine", displayName: "Vending Machine",showImage: true },
{ shortName: "wall.external.high", displayName: "High External Wooden Wall",showImage: true },
{ shortName: "wall.external.high.ice", displayName: "High Ice Wall",showImage: true },
{ shortName: "wall.external.high.stone", displayName: "High External Stone Wall",showImage: true },
{ shortName: "wall.frame.cell", displayName: "Prison Cell Wall",showImage: true },
{ shortName: "wall.frame.cell.gate", displayName: "Prison Cell Gate",showImage: true },
{ shortName: "wall.frame.fence", displayName: "Chainlink Fence",showImage: true },
{ shortName: "wall.frame.fence.gate", displayName: "Chainlink Fence Gate",showImage: true },
{ shortName: "wall.frame.garagedoor", displayName: "Garage Door",showImage: true },
{ shortName: "wall.frame.netting", displayName: "Netting",showImage: true },
{ shortName: "wall.frame.shopfront", displayName: "Shop Front",showImage: true },
{ shortName: "wall.frame.shopfront.metal", displayName: "Metal Shop Front",showImage: true },
{ shortName: "wall.graveyard.fence", displayName: "Graveyard Fence",showImage: true },
{ shortName: "wall.ice.wall", displayName: "Short Ice Wall",showImage: true },
{ shortName: "wall.window.bars.metal", displayName: "Metal Window Bars",showImage: true },
{ shortName: "wall.window.bars.toptier", displayName: "Reinforced Glass Window",showImage: true },
{ shortName: "wall.window.bars.wood", displayName: "Wooden Window Bars",showImage: true },
{ shortName: "wall.window.glass.reinforced", displayName: "Strengthened Glass Window",showImage: true },
{ shortName: "watchtower.wood", displayName: "Watch Tower",showImage: true },
{ shortName: "water", displayName: "Water",showImage: true },
{ shortName: "water.barrel", displayName: "Water Barrel",showImage: true },
{ shortName: "water.catcher.large", displayName: "Large Water Catcher",showImage: true },
{ shortName: "water.catcher.small", displayName: "Small Water Catcher",showImage: true },
{ shortName: "water.purifier", displayName: "Water Purifier",showImage: true },
{ shortName: "water.salt", displayName: "Salt Water",showImage: true },
{ shortName: "waterjug", displayName: "Water Jug",showImage: true },
{ shortName: "waterpump", displayName: "Water Pump",showImage: true },
{ shortName: "weapon.mod.8x.scope", displayName: "16x Zoom Scope",showImage: true },
{ shortName: "weapon.mod.flashlight", displayName: "Weapon flashlight",showImage: true },
{ shortName: "weapon.mod.holosight", displayName: "Holosight",showImage: true },
{ shortName: "weapon.mod.lasersight", displayName: "Weapon Lasersight",showImage: true },
{ shortName: "weapon.mod.muzzleboost", displayName: "Muzzle Boost",showImage: true },
{ shortName: "weapon.mod.muzzlebrake", displayName: "Muzzle Brake",showImage: true },
{ shortName: "weapon.mod.silencer", displayName: "Silencer",showImage: true },
{ shortName: "weapon.mod.simplesight", displayName: "Simple Handmade Sight",showImage: true },
{ shortName: "weapon.mod.small.scope", displayName: "8x Zoom Scope",showImage: true },
{ shortName: "white.berry", displayName: "White Berry",showImage: true },
{ shortName: "wiretool", displayName: "Wire Tool",showImage: true },
{ shortName: "wolfmeat.burned", displayName: "Burnt Wolf Meat",showImage: true },
{ shortName: "wolfmeat.cooked", displayName: "Cooked Wolf Meat",showImage: true },
{ shortName: "wolfmeat.raw", displayName: "Raw Wolf Meat",showImage: true },
{ shortName: "wolfmeat.spoiled", displayName: "Spoiled Wolf Meat",showImage: true },
{ shortName: "wood", displayName: "Wood",showImage: true },
{ shortName: "wood.armor.helmet", displayName: "Wood Armor Helmet",showImage: true },
{ shortName: "wood.armor.jacket", displayName: "Wood Chestplate",showImage: true },
{ shortName: "wood.armor.pants", displayName: "Wood Armor Pants",showImage: true },
{ shortName: "woodcross", displayName: "Wooden Cross",showImage: true },
{ shortName: "woodtea", displayName: "Basic Wood Tea",showImage: true },
{ shortName: "woodtea.advanced", displayName: "Advanced Wood Tea",showImage: true },
{ shortName: "woodtea.pure", displayName: "Pure Wood Tea",showImage: true },
{ shortName: "workbench1", displayName: "Work Bench Level 1",showImage: true },
{ shortName: "workbench2", displayName: "Work Bench Level 2",showImage: true },
{ shortName: "workbench3", displayName: "Work Bench Level 3",showImage: true },
{ shortName: "workcart", displayName: "Work Cart",showImage: true },
{ shortName: "worm", displayName: "Worm",showImage: true },
{ shortName: "wrappedgift", displayName: "Wrapped Gift",showImage: true },
{ shortName: "wrappingpaper", displayName: "Wrapping Paper",showImage: true },
{ shortName: "xmas.decoration.baubels", displayName: "Decorative Baubels",showImage: true },
{ shortName: "xmas.decoration.candycanes", displayName: "Decorative Plastic Candy Canes",showImage: true },
{ shortName: "xmas.decoration.gingerbreadmen", displayName: "Decorative Gingerbread Men",showImage: true },
{ shortName: "xmas.decoration.lights", displayName: "Tree Lights",showImage: true },
{ shortName: "xmas.decoration.pinecone", displayName: "Decorative Pinecones",showImage: true },
{ shortName: "xmas.decoration.star", displayName: "Star Tree Topper",showImage: true },
{ shortName: "xmas.decoration.tinsel", displayName: "Decorative Tinsel",showImage: true },
{ shortName: "xmas.door.garland", displayName: "Festive Doorway Garland",showImage: true },
{ shortName: "xmas.lightstring", displayName: "Christmas Lights",showImage: true },
{ shortName: "xmas.lightstring.advanced", displayName: "Deluxe Christmas Lights",showImage: true },
{ shortName: "xmas.present.large", displayName: "Large Present",showImage: true },
{ shortName: "xmas.present.medium", displayName: "Medium Present",showImage: true },
{ shortName: "xmas.present.small", displayName: "Small Present",showImage: true },
{ shortName: "xmas.tree", displayName: "Christmas Tree",showImage: true },
{ shortName: "xmas.window.garland", displayName: "Festive Window Garland",showImage: true },
{ shortName: "xmasdoorwreath", displayName: "Christmas Door Wreath",showImage: true },
{ shortName: "xylophone", displayName: "Xylobone",showImage: true },
{ shortName: "yellow.berry", displayName: "Yellow Berry",showImage: true },

]; 
console.log(items);

// Function to get a random static image URL (you can adjust the logic as per your static image choices)
const getRandomStaticImage = () => {
  const staticImages = [
    'https://via.placeholder.com/150?text=Static+Image+1',
    'https://via.placeholder.com/150?text=Static+Image+2',
    'https://via.placeholder.com/150?text=Static+Image+3'
  ];
  const randomIndex = Math.floor(Math.random() * staticImages.length);
  return staticImages[randomIndex];
};

// Dynamically build the dropdown list
const buildDropdown = () => {
  const itemDropdown = document.getElementById('itemDropdown');
  itemDropdown.innerHTML = ''; // Clear previous items

  items.forEach(item => {
    const dropdownItem = document.createElement('div');
    dropdownItem.className = 'dropdown-item';
    dropdownItem.dataset.value = item.shortName;

    // Check if the item has the showImage flag set to true, then show either dynamic or static image
    const imageUrl = item.showImage
      ? `https://raw.githubusercontent.com/GorillaPerson/Rust-items-images/refs/heads/main/items/${item.shortName}.png`
      : getRandomStaticImage();

    dropdownItem.innerHTML = `
      <img src="${imageUrl}" alt="${item.displayName}">
      ${item.displayName}
    `;
    itemDropdown.appendChild(dropdownItem);
  });
};

// Call the function to build the dropdown when the script is loaded
document.addEventListener('DOMContentLoaded', buildDropdown);
